-- Contracts foundation: the contract record itself, its taxonomy, its parties,
-- and the per-company configuration those depend on.
--
-- Conventions used throughout this schema:
--   * BIGINT identity primary keys, plus a UUID for anything a URL or another
--     product may reference — sequential ids in a URL are an enumeration hint.
--   * (environment, cmp_id) on every tenant-owned table. environment looks
--     redundant while each deployment has its own database, and stops being
--     redundant the first time a production dump is restored into sandbox.
--   * Bare TIMESTAMP columns holding UTC. The connection pins `SET TIME ZONE
--     'UTC'` (App\Core\Database), so every stored instant means one thing.
--   * JSONB only for genuinely open-ended metadata. Anything filtered,
--     summed or sorted gets a real column.

-- ---------------------------------------------------------------------------
-- Per-company Contracts settings
-- ---------------------------------------------------------------------------
CREATE TABLE contract_settings (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    environment           VARCHAR(16)  NOT NULL,
    cmp_id                BIGINT       NOT NULL,

    number_prefix         VARCHAR(16)  NOT NULL DEFAULT 'CON',
    number_pad            SMALLINT     NOT NULL DEFAULT 6,
    number_include_year   BOOLEAN      NOT NULL DEFAULT TRUE,
    number_reset_yearly   BOOLEAN      NOT NULL DEFAULT TRUE,

    default_currency      VARCHAR(3)   NOT NULL DEFAULT 'INR',
    default_notice_days   SMALLINT     NOT NULL DEFAULT 30,
    expiry_alert_days     VARCHAR(64)  NOT NULL DEFAULT '90,60,30,15,7',
    obligation_alert_days VARCHAR(64)  NOT NULL DEFAULT '14,7,1',
    approval_escalation_days SMALLINT  NOT NULL DEFAULT 3,

    ai_enabled            BOOLEAN      NOT NULL DEFAULT TRUE,
    ai_auto_extract       BOOLEAN      NOT NULL DEFAULT TRUE,
    ai_auto_risk          BOOLEAN      NOT NULL DEFAULT TRUE,

    -- Which role a company member gets when nobody has granted them one.
    -- Mirrors Drive's DOCS_COMPANY_DEFAULT_ACCESS idea: a company that has not
    -- configured Contracts should still be usable, without that meaning
    -- everyone can approve their own contracts.
    default_role          VARCHAR(32)  NOT NULL DEFAULT 'read_only',

    settings_json         JSONB        NOT NULL DEFAULT '{}'::jsonb,
    created_at            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_contract_settings_tenant UNIQUE (environment, cmp_id),
    CONSTRAINT ck_contract_settings_pad CHECK (number_pad BETWEEN 3 AND 12)
);

-- ---------------------------------------------------------------------------
-- Contract types — configurable, never hard-coded in business logic
-- ---------------------------------------------------------------------------
CREATE TABLE contract_types (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                UUID         NOT NULL DEFAULT gen_random_uuid(),
    environment         VARCHAR(16)  NOT NULL,
    -- cmp_id 0 marks a system seed every company inherits until it customises
    -- one. Cloning on first edit keeps one company's rename from moving another
    -- company's contracts to a different type.
    cmp_id              BIGINT       NOT NULL,
    code                VARCHAR(64)  NOT NULL,
    name                VARCHAR(160) NOT NULL,
    description         TEXT         NULL,
    category            VARCHAR(64)  NOT NULL DEFAULT 'general',
    counterparty_side   VARCHAR(16)  NOT NULL DEFAULT 'either',

    default_renewal_type    VARCHAR(24) NULL,
    default_notice_days     SMALLINT    NULL,
    default_term_months     SMALLINT    NULL,

    required_fields     JSONB        NOT NULL DEFAULT '[]'::jsonb,
    mandatory_clauses   JSONB        NOT NULL DEFAULT '[]'::jsonb,
    default_template_id BIGINT       NULL,
    approval_workflow_id BIGINT      NULL,

    is_system           BOOLEAN      NOT NULL DEFAULT FALSE,
    is_active           BOOLEAN      NOT NULL DEFAULT TRUE,
    sort_order          INTEGER      NOT NULL DEFAULT 100,
    created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_contract_types_code UNIQUE (environment, cmp_id, code),
    CONSTRAINT ck_contract_types_side CHECK (counterparty_side IN ('customer', 'vendor', 'internal', 'either'))
);

CREATE INDEX idx_contract_types_tenant ON contract_types (environment, cmp_id, is_active);

-- ---------------------------------------------------------------------------
-- Departments (Contracts-owned; Manage does not model these)
-- ---------------------------------------------------------------------------
CREATE TABLE contract_departments (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    environment  VARCHAR(16)  NOT NULL,
    cmp_id       BIGINT       NOT NULL,
    name         VARCHAR(120) NOT NULL,
    code         VARCHAR(48)  NOT NULL,
    head_uuid    VARCHAR(64)  NULL,
    is_active    BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_contract_departments_code UNIQUE (environment, cmp_id, code)
);

-- ---------------------------------------------------------------------------
-- Role grants — Contracts' own RBAC
-- ---------------------------------------------------------------------------
CREATE TABLE contract_user_roles (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    environment  VARCHAR(16)  NOT NULL,
    cmp_id       BIGINT       NOT NULL,
    user_uuid    VARCHAR(64)  NOT NULL,
    role_slug    VARCHAR(32)  NOT NULL,
    department_id BIGINT      NULL REFERENCES contract_departments (id) ON DELETE SET NULL,
    granted_by   VARCHAR(64)  NULL,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_contract_user_roles UNIQUE (environment, cmp_id, user_uuid, role_slug)
);

CREATE INDEX idx_contract_user_roles_lookup ON contract_user_roles (environment, cmp_id, user_uuid);

-- ---------------------------------------------------------------------------
-- Tags
-- ---------------------------------------------------------------------------
CREATE TABLE contract_tags (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    environment VARCHAR(16)  NOT NULL,
    cmp_id      BIGINT       NOT NULL,
    name        VARCHAR(64)  NOT NULL,
    colour      VARCHAR(16)  NOT NULL DEFAULT 'slate',
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_contract_tags_name UNIQUE (environment, cmp_id, name)
);

-- ---------------------------------------------------------------------------
-- The contract record
-- ---------------------------------------------------------------------------
CREATE TABLE contracts (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid               UUID         NOT NULL DEFAULT gen_random_uuid(),
    environment        VARCHAR(16)  NOT NULL,
    cmp_id             BIGINT       NOT NULL,
    bo_id              BIGINT       NULL,
    fy_id              BIGINT       NULL,

    contract_number    VARCHAR(48)  NOT NULL,
    title              VARCHAR(255) NOT NULL,
    description        TEXT         NULL,

    contract_type_id   BIGINT       NULL REFERENCES contract_types (id) ON DELETE SET NULL,
    department_id      BIGINT       NULL REFERENCES contract_departments (id) ON DELETE SET NULL,
    owner_uuid         VARCHAR(64)  NULL,

    status             VARCHAR(32)  NOT NULL DEFAULT 'draft',
    lifecycle_stage    VARCHAR(32)  NOT NULL DEFAULT 'draft',
    source             VARCHAR(24)  NOT NULL DEFAULT 'drafted',

    -- Dates. effective_date is when the agreement's terms begin; execution_date
    -- is when it was signed. They differ often enough (backdated agreements,
    -- signature after go-live) that collapsing them loses real information.
    effective_date     DATE         NULL,
    commencement_date  DATE         NULL,
    execution_date     DATE         NULL,
    expiry_date        DATE         NULL,

    renewal_type       VARCHAR(24)  NOT NULL DEFAULT 'fixed_term',
    renewal_frequency  VARCHAR(24)  NULL,
    auto_renewal       BOOLEAN      NOT NULL DEFAULT FALSE,
    notice_period_days SMALLINT     NULL,
    -- Derived from expiry_date - notice_period_days and stored, not computed on
    -- read: the renewal sweep filters on it every night across every tenant,
    -- and an index on a stored column is the difference between a scan and a
    -- range seek.
    notice_deadline    DATE         NULL,
    termination_notes  TEXT         NULL,

    governing_law      VARCHAR(120) NULL,
    jurisdiction       VARCHAR(120) NULL,

    currency           VARCHAR(3)   NOT NULL DEFAULT 'INR',
    total_value        NUMERIC(18,2) NULL,
    recurring_value    NUMERIC(18,2) NULL,
    payment_frequency  VARCHAR(24)  NULL,
    billing_frequency  VARCHAR(24)  NULL,
    commercial_summary TEXT         NULL,

    risk_level         VARCHAR(16)  NULL,
    ai_risk_score      SMALLINT     NULL,
    health_score       SMALLINT     NULL,

    approval_status    VARCHAR(24)  NOT NULL DEFAULT 'not_required',
    signing_status     VARCHAR(24)  NOT NULL DEFAULT 'not_started',

    -- Amendment chain. A child amendment contract points at its master; the
    -- master is never rewritten, which is what makes "what did we actually
    -- agree to" answerable at any point in time.
    parent_contract_id BIGINT       NULL REFERENCES contracts (id) ON DELETE SET NULL,
    request_id         BIGINT       NULL,
    template_id        BIGINT       NULL,

    verification_state VARCHAR(24)  NOT NULL DEFAULT 'human_verified',
    notes              TEXT         NULL,
    custom_fields      JSONB        NOT NULL DEFAULT '{}'::jsonb,
    metadata           JSONB        NOT NULL DEFAULT '{}'::jsonb,

    -- Denormalised counterparty name so the repository list does not need a
    -- join (or a Contacts round trip) to render a row.
    counterparty_name  VARCHAR(255) NULL,

    search_vector      TSVECTOR     NULL,

    archived_at        TIMESTAMP    NULL,
    created_by         VARCHAR(64)  NULL,
    updated_by         VARCHAR(64)  NULL,
    created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_contracts_number UNIQUE (environment, cmp_id, contract_number),
    CONSTRAINT uq_contracts_uuid UNIQUE (uuid),
    CONSTRAINT ck_contracts_status CHECK (status IN (
        'draft','under_review','awaiting_approval','approved','negotiation',
        'awaiting_signature','active','renewal_review','expired','terminated',
        'cancelled','archived')),
    CONSTRAINT ck_contracts_stage CHECK (lifecycle_stage IN (
        'request','draft','analysis','internal_review','approval','negotiation',
        'signature','active','obligations','renewal','closed')),
    CONSTRAINT ck_contracts_source CHECK (source IN ('drafted','uploaded','imported','from_request','from_template')),
    CONSTRAINT ck_contracts_renewal_type CHECK (renewal_type IN ('fixed_term','auto_renew','perpetual','evergreen','none')),
    CONSTRAINT ck_contracts_risk CHECK (risk_level IS NULL OR risk_level IN ('low','medium','high','critical')),
    CONSTRAINT ck_contracts_risk_score CHECK (ai_risk_score IS NULL OR ai_risk_score BETWEEN 0 AND 100),
    CONSTRAINT ck_contracts_health CHECK (health_score IS NULL OR health_score BETWEEN 0 AND 100),
    CONSTRAINT ck_contracts_verification CHECK (verification_state IN ('ai_extracted','human_verified','human_edited','rejected')),
    CONSTRAINT ck_contracts_currency CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_contracts_notice CHECK (notice_period_days IS NULL OR notice_period_days BETWEEN 0 AND 3650),
    -- A contract that expires before it starts is a data-entry slip that would
    -- otherwise show up months later as a renewal that never fires.
    CONSTRAINT ck_contracts_dates CHECK (expiry_date IS NULL OR effective_date IS NULL OR expiry_date >= effective_date),
    CONSTRAINT ck_contracts_self_parent CHECK (parent_contract_id IS NULL OR parent_contract_id <> id)
);

CREATE INDEX idx_contracts_tenant_status ON contracts (environment, cmp_id, status) WHERE archived_at IS NULL;
CREATE INDEX idx_contracts_tenant_expiry ON contracts (environment, cmp_id, expiry_date) WHERE archived_at IS NULL;
CREATE INDEX idx_contracts_notice_deadline ON contracts (environment, notice_deadline) WHERE archived_at IS NULL AND notice_deadline IS NOT NULL;
CREATE INDEX idx_contracts_owner ON contracts (environment, cmp_id, owner_uuid);
CREATE INDEX idx_contracts_type ON contracts (environment, cmp_id, contract_type_id);
CREATE INDEX idx_contracts_parent ON contracts (parent_contract_id) WHERE parent_contract_id IS NOT NULL;
CREATE INDEX idx_contracts_search ON contracts USING GIN (search_vector);
CREATE INDEX idx_contracts_updated ON contracts (environment, cmp_id, updated_at DESC);
CREATE INDEX idx_contracts_counterparty ON contracts (environment, cmp_id, counterparty_name);

-- ---------------------------------------------------------------------------
-- Tag assignment
-- ---------------------------------------------------------------------------
CREATE TABLE contract_tag_map (
    contract_id BIGINT NOT NULL REFERENCES contracts (id) ON DELETE CASCADE,
    tag_id      BIGINT NOT NULL REFERENCES contract_tags (id) ON DELETE CASCADE,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (contract_id, tag_id)
);

CREATE INDEX idx_contract_tag_map_tag ON contract_tag_map (tag_id);

-- ---------------------------------------------------------------------------
-- Parties, and the legal snapshot taken at execution
-- ---------------------------------------------------------------------------
CREATE TABLE contract_parties (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                UUID         NOT NULL DEFAULT gen_random_uuid(),
    contract_id         BIGINT       NOT NULL REFERENCES contracts (id) ON DELETE CASCADE,
    environment         VARCHAR(16)  NOT NULL,
    cmp_id              BIGINT       NOT NULL,

    party_role          VARCHAR(32)  NOT NULL,
    is_primary          BOOLEAN      NOT NULL DEFAULT FALSE,

    -- Reference into Contacts. Contracts never copies the contact master; it
    -- keeps the id and re-reads the live record for display.
    contact_ref_id      VARCHAR(64)  NULL,
    contact_ref_type    VARCHAR(32)  NULL,

    display_name        VARCHAR(255) NOT NULL,
    signatory_name      VARCHAR(160) NULL,
    signatory_designation VARCHAR(160) NULL,
    signatory_email     VARCHAR(255) NULL,
    signatory_phone     VARCHAR(48)  NULL,
    notes               TEXT         NULL,

    created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_contract_parties_role CHECK (party_role IN (
        'company','counterparty','customer','vendor','supplier','partner',
        'employee','consultant','landlord','tenant','licensor','licensee',
        'guarantor','witness','other'))
);

CREATE INDEX idx_contract_parties_contract ON contract_parties (contract_id);
CREATE INDEX idx_contract_parties_contact_ref ON contract_parties (environment, cmp_id, contact_ref_id);

-- The snapshot exists because the Contacts master is a living record and a
-- contract is not: renaming a company in Contacts must not silently restate who
-- signed an agreement two years ago. Rows here are append-only — a correction
-- is a new snapshot, never an UPDATE.
CREATE TABLE contract_party_snapshots (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_id          BIGINT      NOT NULL REFERENCES contract_parties (id) ON DELETE CASCADE,
    contract_id       BIGINT      NOT NULL REFERENCES contracts (id) ON DELETE CASCADE,
    environment       VARCHAR(16) NOT NULL,
    cmp_id            BIGINT      NOT NULL,

    captured_reason   VARCHAR(48) NOT NULL DEFAULT 'execution',
    legal_name        VARCHAR(255) NULL,
    trading_name      VARCHAR(255) NULL,
    registered_address TEXT        NULL,
    gstin             VARCHAR(32)  NULL,
    pan               VARCHAR(24)  NULL,
    cin               VARCHAR(32)  NULL,
    email             VARCHAR(255) NULL,
    phone             VARCHAR(48)  NULL,
    authorised_representative VARCHAR(160) NULL,
    representative_designation VARCHAR(160) NULL,
    raw_payload       JSONB        NOT NULL DEFAULT '{}'::jsonb,

    captured_by       VARCHAR(64)  NULL,
    captured_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_party_snapshots_party ON contract_party_snapshots (party_id, captured_at DESC);
CREATE INDEX idx_party_snapshots_contract ON contract_party_snapshots (contract_id);

-- ---------------------------------------------------------------------------
-- Custom fields
-- ---------------------------------------------------------------------------
CREATE TABLE contract_custom_fields (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    environment      VARCHAR(16)  NOT NULL,
    cmp_id           BIGINT       NOT NULL,
    field_key        VARCHAR(64)  NOT NULL,
    label            VARCHAR(160) NOT NULL,
    field_type       VARCHAR(32)  NOT NULL,
    contract_type_id BIGINT       NULL REFERENCES contract_types (id) ON DELETE CASCADE,
    options          JSONB        NOT NULL DEFAULT '[]'::jsonb,
    is_required      BOOLEAN      NOT NULL DEFAULT FALSE,
    is_filterable    BOOLEAN      NOT NULL DEFAULT FALSE,
    help_text        VARCHAR(255) NULL,
    sort_order       INTEGER      NOT NULL DEFAULT 100,
    is_active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_custom_fields_key UNIQUE (environment, cmp_id, field_key),
    CONSTRAINT ck_custom_fields_type CHECK (field_type IN (
        'text','textarea','number','currency','date','boolean',
        'select','multi_select','contact_reference','user_reference')),
    -- field_key reaches a JSONB path; restricting it to an identifier shape
    -- keeps that a lookup rather than an injection surface.
    CONSTRAINT ck_custom_fields_key_shape CHECK (field_key ~ '^[a-z][a-z0-9_]{0,62}$')
);

-- ---------------------------------------------------------------------------
-- Contract numbering counters
-- ---------------------------------------------------------------------------
-- A dedicated counter table rather than a sequence: numbering is per company
-- and optionally resets each year, and one shared sequence cannot do either.
-- Allocation takes a row lock, so two simultaneous creates cannot both take
-- CON-2026-000142.
CREATE TABLE contract_number_counters (
    environment VARCHAR(16) NOT NULL,
    cmp_id      BIGINT      NOT NULL,
    series_key  VARCHAR(32) NOT NULL,
    last_value  BIGINT      NOT NULL DEFAULT 0,
    updated_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (environment, cmp_id, series_key)
);
