-- Contract documents and their version history.
--
-- Contracts owns metadata, lifecycle and version lineage. The bytes live in
-- AICOUNTLY Drive under product_code='contracts' — see docs/DRIVE_INTEGRATION.md.
-- `drive_document_id` is the handle; nothing here ever stores file content.
--
-- The fallback columns exist because Drive can be unconfigured on a fresh
-- install, and a contract product that cannot accept a PDF until object storage
-- is provisioned is not usable. Local storage is opt-in, bounded, and reported
-- as degraded by /api/health.

CREATE TABLE contract_documents (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid               UUID         NOT NULL DEFAULT gen_random_uuid(),
    environment        VARCHAR(16)  NOT NULL,
    cmp_id             BIGINT       NOT NULL,
    contract_id        BIGINT       NULL REFERENCES contracts (id) ON DELETE CASCADE,
    request_id         BIGINT       NULL,
    amendment_id       BIGINT       NULL,

    doc_kind           VARCHAR(32)  NOT NULL DEFAULT 'contract',
    title              VARCHAR(255) NOT NULL,
    description        TEXT         NULL,

    current_version_id BIGINT       NULL,
    version_count      SMALLINT     NOT NULL DEFAULT 0,
    is_executed_copy   BOOLEAN      NOT NULL DEFAULT FALSE,

    created_by         VARCHAR(64)  NULL,
    created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_contract_documents_kind CHECK (doc_kind IN (
        'contract','annexure','schedule','amendment','evidence','executed_copy',
        'correspondence','request_attachment','template','other')),
    -- Every document belongs to exactly one owner record. Without this a row
    -- can be orphaned by a cascade and become invisible but undeletable.
    CONSTRAINT ck_contract_documents_owner CHECK (
        contract_id IS NOT NULL OR request_id IS NOT NULL OR amendment_id IS NOT NULL
    )
);

CREATE INDEX idx_contract_documents_contract ON contract_documents (contract_id);
CREATE INDEX idx_contract_documents_request ON contract_documents (request_id) WHERE request_id IS NOT NULL;
CREATE INDEX idx_contract_documents_tenant ON contract_documents (environment, cmp_id);

CREATE TABLE contract_document_versions (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid              UUID         NOT NULL DEFAULT gen_random_uuid(),
    document_id       BIGINT       NOT NULL REFERENCES contract_documents (id) ON DELETE CASCADE,
    environment       VARCHAR(16)  NOT NULL,
    cmp_id            BIGINT       NOT NULL,

    version_no        SMALLINT     NOT NULL,
    version_status    VARCHAR(32)  NOT NULL DEFAULT 'internal_draft',
    source            VARCHAR(32)  NOT NULL DEFAULT 'internal',
    notes             TEXT         NULL,

    filename          VARCHAR(255) NOT NULL,
    content_type      VARCHAR(128) NOT NULL,
    size_bytes        BIGINT       NOT NULL DEFAULT 0,
    -- SHA-256 of the stored bytes. Two versions with the same checksum are the
    -- same file, which is how "counterparty returned it unchanged" is detected
    -- without diffing megabytes of PDF.
    checksum_sha256   CHAR(64)     NULL,

    storage_provider  VARCHAR(16)  NOT NULL DEFAULT 'drive',
    drive_document_id VARCHAR(64)  NULL,
    drive_version_ref VARCHAR(128) NULL,
    local_path        VARCHAR(512) NULL,

    -- Extracted plain text, kept for search, diffing and AI grounding. Nullable
    -- because extraction is asynchronous and a scanned PDF may never yield any.
    extracted_text    TEXT         NULL,
    extracted_pages   SMALLINT     NULL,
    text_extracted_at TIMESTAMP    NULL,
    is_scanned        BOOLEAN      NOT NULL DEFAULT FALSE,

    is_executed       BOOLEAN      NOT NULL DEFAULT FALSE,
    uploaded_by       VARCHAR(64)  NULL,
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_document_versions_no UNIQUE (document_id, version_no),
    CONSTRAINT ck_document_versions_status CHECK (version_status IN (
        'internal_draft','legal_review','sent_to_counterparty',
        'counterparty_redline','final_draft','executed','superseded')),
    CONSTRAINT ck_document_versions_provider CHECK (storage_provider IN ('drive','local')),
    CONSTRAINT ck_document_versions_no CHECK (version_no > 0),
    CONSTRAINT ck_document_versions_checksum CHECK (checksum_sha256 IS NULL OR checksum_sha256 ~ '^[0-9a-f]{64}$'),
    -- A version with neither a Drive handle nor a local file is a row pointing
    -- at nothing; refusing it here beats discovering it at download time.
    CONSTRAINT ck_document_versions_location CHECK (
        (storage_provider = 'drive' AND drive_document_id IS NOT NULL)
        OR (storage_provider = 'local' AND local_path IS NOT NULL)
    )
);

CREATE INDEX idx_document_versions_document ON contract_document_versions (document_id, version_no DESC);
CREATE INDEX idx_document_versions_checksum ON contract_document_versions (environment, cmp_id, checksum_sha256);

ALTER TABLE contract_documents
    ADD CONSTRAINT fk_contract_documents_current_version
    FOREIGN KEY (current_version_id) REFERENCES contract_document_versions (id) ON DELETE SET NULL;

-- Pending uploads. A row is created before the bytes exist so an abandoned
-- upload leaves a reapable record instead of an orphaned object in Drive.
CREATE TABLE contract_upload_sessions (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_token     CHAR(32)     NOT NULL,
    environment       VARCHAR(16)  NOT NULL,
    cmp_id            BIGINT       NOT NULL,
    bo_id             BIGINT       NULL,
    fy_id             BIGINT       NULL,
    created_by        VARCHAR(64)  NOT NULL,

    contract_id       BIGINT       NULL REFERENCES contracts (id) ON DELETE CASCADE,
    request_id        BIGINT       NULL,
    document_id       BIGINT       NULL REFERENCES contract_documents (id) ON DELETE CASCADE,
    doc_kind          VARCHAR(32)  NOT NULL DEFAULT 'contract',
    version_status    VARCHAR(32)  NOT NULL DEFAULT 'internal_draft',

    filename          VARCHAR(255) NOT NULL,
    content_type      VARCHAR(128) NOT NULL,
    declared_size     BIGINT       NOT NULL DEFAULT 0,

    status            VARCHAR(24)  NOT NULL DEFAULT 'pending',
    storage_provider  VARCHAR(16)  NOT NULL DEFAULT 'drive',
    drive_session_id  VARCHAR(64)  NULL,
    drive_document_id VARCHAR(64)  NULL,
    upload_url        TEXT         NULL,
    local_path        VARCHAR(512) NULL,
    error_message     TEXT         NULL,

    expires_at        TIMESTAMP    NOT NULL,
    completed_at      TIMESTAMP    NULL,
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_upload_sessions_token UNIQUE (session_token),
    CONSTRAINT ck_upload_sessions_status CHECK (status IN ('pending','uploaded','finalized','aborted','expired','failed'))
);

CREATE INDEX idx_upload_sessions_expiry ON contract_upload_sessions (status, expires_at);
CREATE INDEX idx_upload_sessions_tenant ON contract_upload_sessions (environment, cmp_id, created_by);

-- Version comparison results, cached because a deterministic diff over two
-- long contracts is expensive and its inputs are immutable.
CREATE TABLE contract_version_comparisons (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    environment      VARCHAR(16) NOT NULL,
    cmp_id           BIGINT      NOT NULL,
    contract_id      BIGINT      NOT NULL REFERENCES contracts (id) ON DELETE CASCADE,
    base_version_id  BIGINT      NOT NULL REFERENCES contract_document_versions (id) ON DELETE CASCADE,
    target_version_id BIGINT     NOT NULL REFERENCES contract_document_versions (id) ON DELETE CASCADE,

    diff_json        JSONB       NOT NULL DEFAULT '{}'::jsonb,
    stats_json       JSONB       NOT NULL DEFAULT '{}'::jsonb,
    ai_explanation   TEXT        NULL,
    ai_findings      JSONB       NOT NULL DEFAULT '[]'::jsonb,
    generated_by     VARCHAR(64) NULL,
    created_at       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_version_comparison UNIQUE (base_version_id, target_version_id),
    CONSTRAINT ck_version_comparison_distinct CHECK (base_version_id <> target_version_id)
);
