-- Contract requests: the intake queue that precedes a draft.

CREATE TABLE contract_requests (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                 UUID         NOT NULL DEFAULT gen_random_uuid(),
    environment          VARCHAR(16)  NOT NULL,
    cmp_id               BIGINT       NOT NULL,
    bo_id                BIGINT       NULL,

    request_number       VARCHAR(48)  NOT NULL,
    title                VARCHAR(255) NOT NULL,
    contract_type_id     BIGINT       NULL REFERENCES contract_types (id) ON DELETE SET NULL,
    department_id        BIGINT       NULL REFERENCES contract_departments (id) ON DELETE SET NULL,

    requester_uuid       VARCHAR(64)  NOT NULL,
    reviewer_uuid        VARCHAR(64)  NULL,

    required_by_date     DATE         NULL,
    counterparty_name    VARCHAR(255) NULL,
    contact_ref_id       VARCHAR(64)  NULL,

    purpose              TEXT         NULL,
    business_justification TEXT       NULL,
    estimated_value      NUMERIC(18,2) NULL,
    currency             VARCHAR(3)   NOT NULL DEFAULT 'INR',
    preferred_template_id BIGINT      NULL,

    status               VARCHAR(32)  NOT NULL DEFAULT 'draft',
    decision_notes       TEXT         NULL,
    decided_by           VARCHAR(64)  NULL,
    decided_at           TIMESTAMP    NULL,

    -- Set when the request becomes a contract. The request row survives so the
    -- contract can always answer "who asked for this, and why".
    converted_contract_id BIGINT      NULL REFERENCES contracts (id) ON DELETE SET NULL,
    converted_at         TIMESTAMP    NULL,

    notes                TEXT         NULL,
    metadata             JSONB        NOT NULL DEFAULT '{}'::jsonb,
    created_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_contract_requests_number UNIQUE (environment, cmp_id, request_number),
    CONSTRAINT ck_contract_requests_status CHECK (status IN (
        'draft','submitted','under_review','more_info_required',
        'approved_for_drafting','rejected','converted')),
    CONSTRAINT ck_contract_requests_currency CHECK (currency ~ '^[A-Z]{3}$'),
    -- "converted" without a contract to point at would break the link back from
    -- the contract's Activity tab.
    CONSTRAINT ck_contract_requests_converted CHECK (
        status <> 'converted' OR converted_contract_id IS NOT NULL
    )
);

CREATE INDEX idx_contract_requests_tenant ON contract_requests (environment, cmp_id, status);
CREATE INDEX idx_contract_requests_requester ON contract_requests (environment, cmp_id, requester_uuid);
CREATE INDEX idx_contract_requests_contract ON contract_requests (converted_contract_id) WHERE converted_contract_id IS NOT NULL;

ALTER TABLE contracts
    ADD CONSTRAINT fk_contracts_request FOREIGN KEY (request_id)
    REFERENCES contract_requests (id) ON DELETE SET NULL;

ALTER TABLE contract_documents
    ADD CONSTRAINT fk_contract_documents_request FOREIGN KEY (request_id)
    REFERENCES contract_requests (id) ON DELETE CASCADE;

ALTER TABLE contract_upload_sessions
    ADD CONSTRAINT fk_upload_sessions_request FOREIGN KEY (request_id)
    REFERENCES contract_requests (id) ON DELETE CASCADE;
