-- Clause library, templates and the company playbook.
--
-- These three are one subsystem: the playbook says what the company wants, the
-- clause library holds the wording that satisfies it, and templates assemble
-- that wording into a document. The deviation table is where a real contract's
-- clause is measured against the playbook's preference.

CREATE TABLE clause_categories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    environment VARCHAR(16)  NOT NULL,
    cmp_id      BIGINT       NOT NULL,
    code        VARCHAR(64)  NOT NULL,
    name        VARCHAR(160) NOT NULL,
    description TEXT         NULL,
    risk_weight SMALLINT     NOT NULL DEFAULT 5,
    is_system   BOOLEAN      NOT NULL DEFAULT FALSE,
    sort_order  INTEGER      NOT NULL DEFAULT 100,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_clause_categories_code UNIQUE (environment, cmp_id, code),
    CONSTRAINT ck_clause_categories_weight CHECK (risk_weight BETWEEN 0 AND 10)
);

CREATE TABLE clause_library (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid               UUID         NOT NULL DEFAULT gen_random_uuid(),
    environment        VARCHAR(16)  NOT NULL,
    cmp_id             BIGINT       NOT NULL,
    category_id        BIGINT       NULL REFERENCES clause_categories (id) ON DELETE SET NULL,

    name               VARCHAR(200) NOT NULL,
    description        TEXT         NULL,
    standard_text      TEXT         NOT NULL,
    fallback_text      TEXT         NULL,
    prohibited_wording TEXT         NULL,

    risk_classification VARCHAR(16) NOT NULL DEFAULT 'medium',
    applicable_types   JSONB        NOT NULL DEFAULT '[]'::jsonb,
    jurisdiction       VARCHAR(120) NULL,

    version            SMALLINT     NOT NULL DEFAULT 1,
    approval_status    VARCHAR(24)  NOT NULL DEFAULT 'draft',
    effective_from     DATE         NULL,
    effective_to       DATE         NULL,

    author_uuid        VARCHAR(64)  NULL,
    approver_uuid      VARCHAR(64)  NULL,
    approved_at        TIMESTAMP    NULL,
    is_system          BOOLEAN      NOT NULL DEFAULT FALSE,
    archived_at        TIMESTAMP    NULL,
    created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_clause_library_risk CHECK (risk_classification IN ('low','medium','high','critical')),
    CONSTRAINT ck_clause_library_status CHECK (approval_status IN ('draft','approved','deprecated')),
    CONSTRAINT ck_clause_library_dates CHECK (effective_to IS NULL OR effective_from IS NULL OR effective_to >= effective_from)
);

CREATE INDEX idx_clause_library_tenant ON clause_library (environment, cmp_id, approval_status) WHERE archived_at IS NULL;
CREATE INDEX idx_clause_library_category ON clause_library (category_id);

-- Superseded wording is kept, not overwritten: a contract signed last year was
-- reviewed against the clause text as it stood then.
CREATE TABLE clause_versions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clause_id     BIGINT      NOT NULL REFERENCES clause_library (id) ON DELETE CASCADE,
    version       SMALLINT    NOT NULL,
    standard_text TEXT        NOT NULL,
    fallback_text TEXT        NULL,
    change_note   TEXT        NULL,
    author_uuid   VARCHAR(64) NULL,
    created_at    TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_clause_versions UNIQUE (clause_id, version)
);

-- A clause as it actually appears in one contract.
CREATE TABLE contract_clauses (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    environment      VARCHAR(16)  NOT NULL,
    cmp_id           BIGINT       NOT NULL,
    contract_id      BIGINT       NOT NULL REFERENCES contracts (id) ON DELETE CASCADE,
    version_id       BIGINT       NULL REFERENCES contract_document_versions (id) ON DELETE SET NULL,
    category_id      BIGINT       NULL REFERENCES clause_categories (id) ON DELETE SET NULL,
    library_clause_id BIGINT      NULL REFERENCES clause_library (id) ON DELETE SET NULL,

    clause_number    VARCHAR(48)  NULL,
    heading          VARCHAR(255) NULL,
    body_text        TEXT         NOT NULL,

    -- Where in the source document this came from, so a finding can be shown
    -- against the paragraph it is about rather than asserted in the abstract.
    source_page      SMALLINT     NULL,
    source_offset    INTEGER      NULL,
    source_excerpt   TEXT         NULL,

    is_ai_extracted  BOOLEAN      NOT NULL DEFAULT FALSE,
    ai_confidence    NUMERIC(4,3) NULL,
    verification_state VARCHAR(24) NOT NULL DEFAULT 'ai_extracted',
    verified_by      VARCHAR(64)  NULL,
    verified_at      TIMESTAMP    NULL,

    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_contract_clauses_confidence CHECK (ai_confidence IS NULL OR ai_confidence BETWEEN 0 AND 1),
    CONSTRAINT ck_contract_clauses_verification CHECK (verification_state IN ('ai_extracted','human_verified','human_edited','rejected'))
);

CREATE INDEX idx_contract_clauses_contract ON contract_clauses (contract_id);
CREATE INDEX idx_contract_clauses_category ON contract_clauses (environment, cmp_id, category_id);

CREATE TABLE contract_playbooks (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid         UUID         NOT NULL DEFAULT gen_random_uuid(),
    environment  VARCHAR(16)  NOT NULL,
    cmp_id       BIGINT       NOT NULL,
    name         VARCHAR(160) NOT NULL,
    description  TEXT         NULL,
    contract_type_id BIGINT   NULL REFERENCES contract_types (id) ON DELETE CASCADE,
    is_default   BOOLEAN      NOT NULL DEFAULT FALSE,
    is_active    BOOLEAN      NOT NULL DEFAULT TRUE,
    created_by   VARCHAR(64)  NULL,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_contract_playbooks_tenant ON contract_playbooks (environment, cmp_id, is_active);

-- One rule = one company preference, stated in a form a deterministic engine
-- can evaluate before any LLM is asked for an opinion.
CREATE TABLE playbook_rules (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    playbook_id   BIGINT       NOT NULL REFERENCES contract_playbooks (id) ON DELETE CASCADE,
    environment   VARCHAR(16)  NOT NULL,
    cmp_id        BIGINT       NOT NULL,

    rule_key      VARCHAR(64)  NOT NULL,
    category_id   BIGINT       NULL REFERENCES clause_categories (id) ON DELETE SET NULL,
    rule_type     VARCHAR(32)  NOT NULL,
    label         VARCHAR(200) NOT NULL,
    description   TEXT         NULL,

    operator      VARCHAR(24)  NULL,
    expected_value TEXT        NULL,
    expected_numeric NUMERIC(18,2) NULL,
    expected_list JSONB        NOT NULL DEFAULT '[]'::jsonb,

    severity      VARCHAR(16)  NOT NULL DEFAULT 'medium',
    risk_category VARCHAR(32)  NOT NULL DEFAULT 'legal',
    recommendation TEXT        NULL,
    is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
    sort_order    INTEGER      NOT NULL DEFAULT 100,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_playbook_rules_key UNIQUE (playbook_id, rule_key),
    CONSTRAINT ck_playbook_rules_type CHECK (rule_type IN (
        'mandatory_clause','prohibited_clause','preferred_wording','max_numeric',
        'min_numeric','allowed_list','prohibited_list','boolean_flag','date_window')),
    CONSTRAINT ck_playbook_rules_severity CHECK (severity IN ('informational','low','medium','high','critical')),
    CONSTRAINT ck_playbook_rules_risk_cat CHECK (risk_category IN (
        'legal','commercial','financial','compliance','operational',
        'data_protection','renewal','counterparty','sla'))
);

CREATE INDEX idx_playbook_rules_playbook ON playbook_rules (playbook_id, is_active);

CREATE TABLE clause_deviations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    environment     VARCHAR(16)  NOT NULL,
    cmp_id          BIGINT       NOT NULL,
    contract_id     BIGINT       NOT NULL REFERENCES contracts (id) ON DELETE CASCADE,
    clause_id       BIGINT       NULL REFERENCES contract_clauses (id) ON DELETE CASCADE,
    playbook_rule_id BIGINT      NULL REFERENCES playbook_rules (id) ON DELETE SET NULL,
    category_id     BIGINT       NULL REFERENCES clause_categories (id) ON DELETE SET NULL,

    contract_wording  TEXT       NULL,
    preferred_wording TEXT       NULL,
    deviation_summary TEXT       NOT NULL,
    severity        VARCHAR(16)  NOT NULL DEFAULT 'medium',
    recommendation  TEXT         NULL,

    detected_by     VARCHAR(16)  NOT NULL DEFAULT 'rules',
    review_status   VARCHAR(24)  NOT NULL DEFAULT 'open',
    reviewed_by     VARCHAR(64)  NULL,
    reviewed_at     TIMESTAMP    NULL,
    review_notes    TEXT         NULL,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_clause_deviations_severity CHECK (severity IN ('informational','low','medium','high','critical')),
    CONSTRAINT ck_clause_deviations_detected_by CHECK (detected_by IN ('rules','ai','manual')),
    CONSTRAINT ck_clause_deviations_review CHECK (review_status IN ('open','accepted','rejected','negotiating','resolved'))
);

CREATE INDEX idx_clause_deviations_contract ON clause_deviations (contract_id, review_status);

CREATE TABLE contract_templates (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid           UUID         NOT NULL DEFAULT gen_random_uuid(),
    environment    VARCHAR(16)  NOT NULL,
    cmp_id         BIGINT       NOT NULL,
    contract_type_id BIGINT     NULL REFERENCES contract_types (id) ON DELETE SET NULL,

    name           VARCHAR(200) NOT NULL,
    description    TEXT         NULL,
    body           TEXT         NOT NULL DEFAULT '',
    header_html    TEXT         NULL,
    footer_html    TEXT         NULL,

    status         VARCHAR(24)  NOT NULL DEFAULT 'draft',
    version        SMALLINT     NOT NULL DEFAULT 1,
    owner_uuid     VARCHAR(64)  NULL,
    approval_status VARCHAR(24) NOT NULL DEFAULT 'draft',
    approved_by    VARCHAR(64)  NULL,
    approved_at    TIMESTAMP    NULL,

    -- Which merge variables this body actually uses, recomputed on save. The
    -- renderer validates against this rather than trusting whatever the body
    -- happens to contain at render time.
    variables      JSONB        NOT NULL DEFAULT '[]'::jsonb,
    optional_clauses JSONB      NOT NULL DEFAULT '[]'::jsonb,
    signature_blocks JSONB      NOT NULL DEFAULT '[]'::jsonb,
    schedules      JSONB        NOT NULL DEFAULT '[]'::jsonb,
    tags           JSONB        NOT NULL DEFAULT '[]'::jsonb,

    archived_at    TIMESTAMP    NULL,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_contract_templates_status CHECK (status IN ('draft','active','deprecated')),
    CONSTRAINT ck_contract_templates_approval CHECK (approval_status IN ('draft','approved','deprecated'))
);

CREATE INDEX idx_contract_templates_tenant ON contract_templates (environment, cmp_id, status) WHERE archived_at IS NULL;

CREATE TABLE contract_template_versions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id BIGINT      NOT NULL REFERENCES contract_templates (id) ON DELETE CASCADE,
    version     SMALLINT    NOT NULL,
    body        TEXT        NOT NULL,
    variables   JSONB       NOT NULL DEFAULT '[]'::jsonb,
    change_note TEXT        NULL,
    author_uuid VARCHAR(64) NULL,
    created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_template_versions UNIQUE (template_id, version)
);

-- The variable registry. A template may only reference a key that exists here,
-- which is what keeps merge rendering a lookup rather than an evaluation.
CREATE TABLE template_variables (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    environment  VARCHAR(16)  NOT NULL,
    cmp_id       BIGINT       NOT NULL,
    var_key      VARCHAR(96)  NOT NULL,
    label        VARCHAR(160) NOT NULL,
    source       VARCHAR(32)  NOT NULL,
    source_path  VARCHAR(128) NOT NULL,
    data_type    VARCHAR(24)  NOT NULL DEFAULT 'text',
    example      VARCHAR(255) NULL,
    is_system    BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_template_variables_key UNIQUE (environment, cmp_id, var_key),
    CONSTRAINT ck_template_variables_source CHECK (source IN ('company','counterparty','contract','commercial','custom','system')),
    CONSTRAINT ck_template_variables_key_shape CHECK (var_key ~ '^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)*$')
);

ALTER TABLE contract_types
    ADD CONSTRAINT fk_contract_types_template FOREIGN KEY (default_template_id)
    REFERENCES contract_templates (id) ON DELETE SET NULL;

ALTER TABLE contracts
    ADD CONSTRAINT fk_contracts_template FOREIGN KEY (template_id)
    REFERENCES contract_templates (id) ON DELETE SET NULL;

ALTER TABLE contract_requests
    ADD CONSTRAINT fk_contract_requests_template FOREIGN KEY (preferred_template_id)
    REFERENCES contract_templates (id) ON DELETE SET NULL;
