-- Configurable approval routing.
--
-- No approval chain is hard-coded. A workflow's conditions decide whether it
-- applies to a contract; its steps decide who acts and in what order. That is
-- the difference between a product a company can adopt and one it has to be
-- reorganised around.

CREATE TABLE approval_workflows (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid            UUID         NOT NULL DEFAULT gen_random_uuid(),
    environment     VARCHAR(16)  NOT NULL,
    cmp_id          BIGINT       NOT NULL,

    name            VARCHAR(200) NOT NULL,
    description     TEXT         NULL,
    applies_to      VARCHAR(24)  NOT NULL DEFAULT 'contract',

    -- Conditions evaluated against the contract. Stored as JSONB because the
    -- set of comparable attributes grows with the product, and each entry is
    -- validated against a fixed schema before it is written.
    conditions      JSONB        NOT NULL DEFAULT '[]'::jsonb,
    match_mode      VARCHAR(8)   NOT NULL DEFAULT 'all',

    -- Lower runs first; the first matching workflow wins. Without a
    -- deterministic order, two overlapping workflows would route the same
    -- contract differently on different days.
    priority        INTEGER      NOT NULL DEFAULT 100,
    is_active       BOOLEAN      NOT NULL DEFAULT TRUE,
    escalation_days SMALLINT     NULL,

    created_by      VARCHAR(64)  NULL,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_approval_workflows_applies CHECK (applies_to IN ('contract','request','amendment','termination','renewal')),
    CONSTRAINT ck_approval_workflows_match CHECK (match_mode IN ('all','any'))
);

CREATE INDEX idx_approval_workflows_tenant ON approval_workflows (environment, cmp_id, applies_to, is_active, priority);

CREATE TABLE approval_workflow_steps (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id    BIGINT       NOT NULL REFERENCES approval_workflows (id) ON DELETE CASCADE,
    environment    VARCHAR(16)  NOT NULL,
    cmp_id         BIGINT       NOT NULL,

    step_no        SMALLINT     NOT NULL,
    name           VARCHAR(160) NOT NULL,
    -- 'sequential' waits for the previous step; 'parallel' runs alongside the
    -- steps that share its step_no.
    execution      VARCHAR(16)  NOT NULL DEFAULT 'sequential',

    approver_type  VARCHAR(24)  NOT NULL,
    approver_value VARCHAR(128) NULL,
    -- For parallel steps: how many of the assigned approvers must approve.
    min_approvals  SMALLINT     NOT NULL DEFAULT 1,
    can_edit       BOOLEAN      NOT NULL DEFAULT FALSE,
    escalation_days SMALLINT    NULL,
    escalate_to_uuid VARCHAR(64) NULL,

    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_workflow_steps_execution CHECK (execution IN ('sequential','parallel')),
    CONSTRAINT ck_workflow_steps_approver CHECK (approver_type IN ('user','role','department_head','contract_owner','manager')),
    CONSTRAINT ck_workflow_steps_min CHECK (min_approvals >= 1),
    CONSTRAINT ck_workflow_steps_no CHECK (step_no > 0)
);

CREATE INDEX idx_workflow_steps_workflow ON approval_workflow_steps (workflow_id, step_no);

-- One run of a workflow against one record.
CREATE TABLE contract_approval_instances (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid           UUID         NOT NULL DEFAULT gen_random_uuid(),
    environment    VARCHAR(16)  NOT NULL,
    cmp_id         BIGINT       NOT NULL,

    subject_type   VARCHAR(24)  NOT NULL DEFAULT 'contract',
    subject_id     BIGINT       NOT NULL,
    contract_id    BIGINT       NULL REFERENCES contracts (id) ON DELETE CASCADE,
    workflow_id    BIGINT       NULL REFERENCES approval_workflows (id) ON DELETE SET NULL,
    workflow_name  VARCHAR(200) NULL,

    status         VARCHAR(24)  NOT NULL DEFAULT 'pending',
    current_step   SMALLINT     NOT NULL DEFAULT 1,
    -- The step definitions frozen at submission. A workflow edited mid-approval
    -- must not change who was supposed to approve an in-flight contract.
    steps_snapshot JSONB        NOT NULL DEFAULT '[]'::jsonb,

    submitted_by   VARCHAR(64)  NULL,
    submitted_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at   TIMESTAMP    NULL,
    outcome_note   TEXT         NULL,

    CONSTRAINT ck_approval_instances_subject CHECK (subject_type IN ('contract','request','amendment','termination','renewal')),
    CONSTRAINT ck_approval_instances_status CHECK (status IN ('pending','in_progress','approved','rejected','sent_back','cancelled'))
);

CREATE INDEX idx_approval_instances_subject ON contract_approval_instances (environment, cmp_id, subject_type, subject_id);
CREATE INDEX idx_approval_instances_status ON contract_approval_instances (environment, cmp_id, status);

-- Who has to act, and whether they have. Rows are created when a step opens so
-- "my pending approvals" is one indexed read rather than a workflow replay.
CREATE TABLE contract_approval_assignments (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_id   BIGINT       NOT NULL REFERENCES contract_approval_instances (id) ON DELETE CASCADE,
    environment   VARCHAR(16)  NOT NULL,
    cmp_id        BIGINT       NOT NULL,

    step_no       SMALLINT     NOT NULL,
    step_name     VARCHAR(160) NULL,
    approver_uuid VARCHAR(64)  NOT NULL,
    delegated_from VARCHAR(64) NULL,

    status        VARCHAR(24)  NOT NULL DEFAULT 'pending',
    assigned_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    acted_at      TIMESTAMP    NULL,
    due_at        TIMESTAMP    NULL,
    escalated_at  TIMESTAMP    NULL,
    comment       TEXT         NULL,

    CONSTRAINT uq_approval_assignment UNIQUE (instance_id, step_no, approver_uuid),
    CONSTRAINT ck_approval_assignment_status CHECK (status IN ('pending','approved','rejected','sent_back','reassigned','skipped'))
);

CREATE INDEX idx_approval_assignments_approver ON contract_approval_assignments (environment, cmp_id, approver_uuid, status);
CREATE INDEX idx_approval_assignments_due ON contract_approval_assignments (status, due_at) WHERE status = 'pending';

-- Append-only record of every approval action taken.
CREATE TABLE contract_approval_actions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_id   BIGINT       NOT NULL REFERENCES contract_approval_instances (id) ON DELETE CASCADE,
    assignment_id BIGINT       NULL REFERENCES contract_approval_assignments (id) ON DELETE SET NULL,
    environment   VARCHAR(16)  NOT NULL,
    cmp_id        BIGINT       NOT NULL,

    step_no       SMALLINT     NOT NULL,
    actor_uuid    VARCHAR(64)  NOT NULL,
    action        VARCHAR(24)  NOT NULL,
    comment       TEXT         NULL,
    reassigned_to VARCHAR(64)  NULL,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_approval_actions_action CHECK (action IN ('approve','reject','send_back','request_changes','comment','reassign','escalate','cancel'))
);

CREATE INDEX idx_approval_actions_instance ON contract_approval_actions (instance_id, created_at);
