-- Obligations and milestones — what the agreement actually requires someone to do.
--
-- An obligation is the rule ("submit a quarterly SLA report"); an occurrence is
-- one instance of it falling due. Splitting them is what lets a recurring
-- obligation have a compliance history instead of a single mutable due date.

CREATE TABLE contract_obligations (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid             UUID         NOT NULL DEFAULT gen_random_uuid(),
    environment      VARCHAR(16)  NOT NULL,
    cmp_id           BIGINT       NOT NULL,
    contract_id      BIGINT       NOT NULL REFERENCES contracts (id) ON DELETE CASCADE,
    clause_id        BIGINT       NULL REFERENCES contract_clauses (id) ON DELETE SET NULL,

    obligation_type  VARCHAR(48)  NOT NULL DEFAULT 'general',
    title            VARCHAR(255) NOT NULL,
    description      TEXT         NULL,

    responsible_party VARCHAR(16) NOT NULL DEFAULT 'company',
    owner_uuid       VARCHAR(64)  NULL,

    frequency        VARCHAR(24)  NOT NULL DEFAULT 'one_time',
    custom_interval_days SMALLINT NULL,
    start_date       DATE         NULL,
    end_date         DATE         NULL,
    first_due_date   DATE         NULL,
    grace_period_days SMALLINT    NOT NULL DEFAULT 0,

    amount           NUMERIC(18,2) NULL,
    currency         VARCHAR(3)   NULL,

    evidence_required BOOLEAN     NOT NULL DEFAULT FALSE,
    reminder_days    VARCHAR(64)  NOT NULL DEFAULT '14,7,1',
    escalation_days  SMALLINT     NULL,
    escalate_to_uuid VARCHAR(64)  NULL,

    status           VARCHAR(24)  NOT NULL DEFAULT 'upcoming',
    is_ai_extracted  BOOLEAN      NOT NULL DEFAULT FALSE,
    ai_confidence    NUMERIC(4,3) NULL,
    verification_state VARCHAR(24) NOT NULL DEFAULT 'human_verified',
    verified_by      VARCHAR(64)  NULL,
    verified_at      TIMESTAMP    NULL,

    is_active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_by       VARCHAR(64)  NULL,
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_obligations_responsible CHECK (responsible_party IN ('company','counterparty','both')),
    CONSTRAINT ck_obligations_frequency CHECK (frequency IN (
        'one_time','daily','weekly','fortnightly','monthly','quarterly','half_yearly','annual','custom')),
    CONSTRAINT ck_obligations_status CHECK (status IN (
        'upcoming','due','overdue','completed','waived','not_applicable','disputed')),
    CONSTRAINT ck_obligations_verification CHECK (verification_state IN ('ai_extracted','human_verified','human_edited','rejected')),
    CONSTRAINT ck_obligations_confidence CHECK (ai_confidence IS NULL OR ai_confidence BETWEEN 0 AND 1),
    CONSTRAINT ck_obligations_currency CHECK (currency IS NULL OR currency ~ '^[A-Z]{3}$'),
    -- A custom frequency with no interval would generate no occurrences and
    -- look like a working obligation that silently never fires.
    CONSTRAINT ck_obligations_custom_interval CHECK (
        frequency <> 'custom' OR (custom_interval_days IS NOT NULL AND custom_interval_days > 0)
    )
);

CREATE INDEX idx_obligations_contract ON contract_obligations (contract_id, is_active);
CREATE INDEX idx_obligations_tenant_status ON contract_obligations (environment, cmp_id, status);
CREATE INDEX idx_obligations_owner ON contract_obligations (environment, cmp_id, owner_uuid);

CREATE TABLE obligation_occurrences (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid           UUID         NOT NULL DEFAULT gen_random_uuid(),
    obligation_id  BIGINT       NOT NULL REFERENCES contract_obligations (id) ON DELETE CASCADE,
    contract_id    BIGINT       NOT NULL REFERENCES contracts (id) ON DELETE CASCADE,
    environment    VARCHAR(16)  NOT NULL,
    cmp_id         BIGINT       NOT NULL,

    sequence_no    INTEGER      NOT NULL DEFAULT 1,
    due_date       DATE         NOT NULL,
    grace_until    DATE         NULL,
    period_start   DATE         NULL,
    period_end     DATE         NULL,

    status         VARCHAR(24)  NOT NULL DEFAULT 'upcoming',
    completed_at   TIMESTAMP    NULL,
    completed_by   VARCHAR(64)  NULL,
    completion_note TEXT        NULL,
    amount         NUMERIC(18,2) NULL,

    -- Highest reminder threshold already sent for this occurrence, so a nightly
    -- sweep re-run cannot send the same 7-day warning twice.
    last_reminder_days SMALLINT NULL,
    reminder_sent_at TIMESTAMP  NULL,
    escalated_at   TIMESTAMP    NULL,

    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_obligation_occurrence UNIQUE (obligation_id, due_date),
    CONSTRAINT ck_occurrence_status CHECK (status IN (
        'upcoming','due','overdue','completed','waived','not_applicable','disputed'))
);

CREATE INDEX idx_occurrences_due ON obligation_occurrences (environment, cmp_id, status, due_date);
CREATE INDEX idx_occurrences_contract ON obligation_occurrences (contract_id, due_date);
CREATE INDEX idx_occurrences_sweep ON obligation_occurrences (status, due_date) WHERE status IN ('upcoming','due','overdue');

CREATE TABLE obligation_evidence (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurrence_id BIGINT       NOT NULL REFERENCES obligation_occurrences (id) ON DELETE CASCADE,
    obligation_id BIGINT       NOT NULL REFERENCES contract_obligations (id) ON DELETE CASCADE,
    environment   VARCHAR(16)  NOT NULL,
    cmp_id        BIGINT       NOT NULL,

    document_id   BIGINT       NULL REFERENCES contract_documents (id) ON DELETE SET NULL,
    note          TEXT         NULL,
    external_ref  VARCHAR(255) NULL,
    uploaded_by   VARCHAR(64)  NULL,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_obligation_evidence_occurrence ON obligation_evidence (occurrence_id);

CREATE TABLE contract_milestones (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid           UUID         NOT NULL DEFAULT gen_random_uuid(),
    environment    VARCHAR(16)  NOT NULL,
    cmp_id         BIGINT       NOT NULL,
    contract_id    BIGINT       NOT NULL REFERENCES contracts (id) ON DELETE CASCADE,
    clause_id      BIGINT       NULL REFERENCES contract_clauses (id) ON DELETE SET NULL,

    title          VARCHAR(255) NOT NULL,
    description    TEXT         NULL,
    milestone_type VARCHAR(48)  NOT NULL DEFAULT 'general',
    due_date       DATE         NOT NULL,
    owner_uuid     VARCHAR(64)  NULL,

    amount         NUMERIC(18,2) NULL,
    currency       VARCHAR(3)   NULL,

    status         VARCHAR(24)  NOT NULL DEFAULT 'pending',
    completed_at   TIMESTAMP    NULL,
    completed_by   VARCHAR(64)  NULL,
    depends_on_id  BIGINT       NULL REFERENCES contract_milestones (id) ON DELETE SET NULL,

    reminder_days  VARCHAR(64)  NOT NULL DEFAULT '14,7,1',
    last_reminder_days SMALLINT NULL,
    is_ai_extracted BOOLEAN     NOT NULL DEFAULT FALSE,
    created_by     VARCHAR(64)  NULL,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_milestones_status CHECK (status IN ('pending','in_progress','completed','missed','cancelled')),
    CONSTRAINT ck_milestones_currency CHECK (currency IS NULL OR currency ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_milestones_self_dep CHECK (depends_on_id IS NULL OR depends_on_id <> id)
);

CREATE INDEX idx_milestones_contract ON contract_milestones (contract_id, due_date);
CREATE INDEX idx_milestones_due ON contract_milestones (environment, cmp_id, status, due_date);
