-- Commercial terms and payment schedules.
--
-- Deliberately normalised rather than one JSONB blob: "which contracts commit
-- us to a minimum purchase" and "what are our receivable commitments this
-- quarter" are the questions this product exists to answer, and neither is
-- answerable by filtering inside a JSON document at scale.

CREATE TABLE contract_commercial_terms (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    environment            VARCHAR(16)  NOT NULL,
    cmp_id                 BIGINT       NOT NULL,
    contract_id            BIGINT       NOT NULL REFERENCES contracts (id) ON DELETE CASCADE,

    currency               VARCHAR(3)   NOT NULL DEFAULT 'INR',
    total_value            NUMERIC(18,2) NULL,
    recurring_amount       NUMERIC(18,2) NULL,
    billing_frequency      VARCHAR(24)  NULL,
    payment_terms_days     SMALLINT     NULL,
    payment_terms_note     VARCHAR(255) NULL,

    -- Direction of money. Without it, "receivable commitments" and "payable
    -- commitments" on the dashboard cannot be separated.
    value_direction        VARCHAR(16)  NOT NULL DEFAULT 'receivable',

    advance_amount         NUMERIC(18,2) NULL,
    advance_percent        NUMERIC(6,3) NULL,
    retention_percent      NUMERIC(6,3) NULL,
    security_deposit       NUMERIC(18,2) NULL,
    performance_guarantee  NUMERIC(18,2) NULL,

    penalty_note           TEXT         NULL,
    late_payment_interest  NUMERIC(6,3) NULL,
    escalation_percent     NUMERIC(6,3) NULL,
    escalation_basis       VARCHAR(64)  NULL,
    escalation_frequency   VARCHAR(24)  NULL,

    discount_percent       NUMERIC(6,3) NULL,
    rebate_note            VARCHAR(255) NULL,
    minimum_purchase       NUMERIC(18,2) NULL,
    maximum_purchase       NUMERIC(18,2) NULL,
    minimum_revenue_commitment NUMERIC(18,2) NULL,
    committed_quantity     NUMERIC(18,3) NULL,
    quantity_unit          VARCHAR(32)  NULL,
    unit_rate              NUMERIC(18,4) NULL,

    termination_charge     NUMERIC(18,2) NULL,
    notice_charge          NUMERIC(18,2) NULL,
    renewal_pricing_note   TEXT         NULL,

    -- Anything genuinely contract-specific that does not deserve a column.
    extra                  JSONB        NOT NULL DEFAULT '{}'::jsonb,

    is_ai_extracted        BOOLEAN      NOT NULL DEFAULT FALSE,
    verification_state     VARCHAR(24)  NOT NULL DEFAULT 'human_verified',
    updated_by             VARCHAR(64)  NULL,
    created_at             TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_commercial_terms_contract UNIQUE (contract_id),
    CONSTRAINT ck_commercial_currency CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_commercial_direction CHECK (value_direction IN ('receivable','payable','both','none')),
    CONSTRAINT ck_commercial_percent CHECK (
        (advance_percent IS NULL OR advance_percent BETWEEN 0 AND 100)
        AND (retention_percent IS NULL OR retention_percent BETWEEN 0 AND 100)
        AND (discount_percent IS NULL OR discount_percent BETWEEN 0 AND 100)
    ),
    CONSTRAINT ck_commercial_purchase_range CHECK (
        minimum_purchase IS NULL OR maximum_purchase IS NULL OR maximum_purchase >= minimum_purchase
    ),
    CONSTRAINT ck_commercial_verification CHECK (verification_state IN ('ai_extracted','human_verified','human_edited','rejected'))
);

CREATE INDEX idx_commercial_terms_tenant ON contract_commercial_terms (environment, cmp_id, value_direction);

CREATE TABLE contract_payment_schedules (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    environment   VARCHAR(16)  NOT NULL,
    cmp_id        BIGINT       NOT NULL,
    contract_id   BIGINT       NOT NULL REFERENCES contracts (id) ON DELETE CASCADE,
    milestone_id  BIGINT       NULL REFERENCES contract_milestones (id) ON DELETE SET NULL,

    sequence_no   SMALLINT     NOT NULL DEFAULT 1,
    label         VARCHAR(200) NOT NULL,
    due_date      DATE         NULL,
    amount        NUMERIC(18,2) NOT NULL,
    percent_of_total NUMERIC(6,3) NULL,
    currency      VARCHAR(3)   NOT NULL DEFAULT 'INR',
    direction     VARCHAR(16)  NOT NULL DEFAULT 'receivable',

    status        VARCHAR(24)  NOT NULL DEFAULT 'scheduled',
    settled_at    TIMESTAMP    NULL,
    -- Reference into Books/Billing once that integration is live. Contracts
    -- never copies the voucher; it holds the id and asks.
    external_ref_product VARCHAR(32) NULL,
    external_ref_id      VARCHAR(64) NULL,

    notes         TEXT         NULL,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_payment_schedule_status CHECK (status IN ('scheduled','invoiced','part_paid','settled','waived','overdue')),
    CONSTRAINT ck_payment_schedule_direction CHECK (direction IN ('receivable','payable')),
    CONSTRAINT ck_payment_schedule_currency CHECK (currency ~ '^[A-Z]{3}$')
);

CREATE INDEX idx_payment_schedules_contract ON contract_payment_schedules (contract_id, sequence_no);
CREATE INDEX idx_payment_schedules_due ON contract_payment_schedules (environment, cmp_id, status, due_date);
