-- Renewal, amendment and termination.
--
-- The rule these three share: the original agreement is never rewritten. A
-- renewal decision, an amendment and a termination are all records *about* the
-- contract, so "what did we agree to, and when did that change" stays
-- answerable years later.

CREATE TABLE contract_renewals (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid               UUID         NOT NULL DEFAULT gen_random_uuid(),
    environment        VARCHAR(16)  NOT NULL,
    cmp_id             BIGINT       NOT NULL,
    contract_id        BIGINT       NOT NULL REFERENCES contracts (id) ON DELETE CASCADE,

    cycle_no           SMALLINT     NOT NULL DEFAULT 1,
    current_expiry     DATE         NULL,
    notice_deadline    DATE         NULL,
    decision_due_date  DATE         NULL,
    proposed_start     DATE         NULL,
    proposed_expiry    DATE         NULL,
    renewal_term_months SMALLINT    NULL,

    status             VARCHAR(32)  NOT NULL DEFAULT 'not_yet_due',
    owner_uuid         VARCHAR(64)  NULL,
    recommendation     VARCHAR(24)  NULL,
    recommendation_reason TEXT      NULL,
    recommendation_source VARCHAR(16) NULL,

    decision           VARCHAR(24)  NULL,
    decision_by        VARCHAR(64)  NULL,
    decision_at        TIMESTAMP    NULL,
    decision_notes     TEXT         NULL,
    renegotiation_required BOOLEAN  NOT NULL DEFAULT FALSE,

    renewed_contract_id BIGINT      NULL REFERENCES contracts (id) ON DELETE SET NULL,
    notes              TEXT         NULL,
    created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_contract_renewal_cycle UNIQUE (contract_id, cycle_no),
    CONSTRAINT ck_renewal_status CHECK (status IN (
        'not_yet_due','review_due','under_review','renew','renegotiate',
        'terminate','renewal_in_progress','renewed','closed')),
    CONSTRAINT ck_renewal_recommendation CHECK (recommendation IS NULL OR recommendation IN ('renew','renegotiate','terminate','review_manually')),
    CONSTRAINT ck_renewal_decision CHECK (decision IS NULL OR decision IN ('renew','renegotiate','terminate','defer')),
    CONSTRAINT ck_renewal_source CHECK (recommendation_source IS NULL OR recommendation_source IN ('rules','ai','manual'))
);

CREATE INDEX idx_renewals_contract ON contract_renewals (contract_id, cycle_no DESC);
CREATE INDEX idx_renewals_status ON contract_renewals (environment, cmp_id, status);
CREATE INDEX idx_renewals_deadline ON contract_renewals (environment, notice_deadline) WHERE status IN ('not_yet_due','review_due','under_review');

CREATE TABLE contract_amendments (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid               UUID         NOT NULL DEFAULT gen_random_uuid(),
    environment        VARCHAR(16)  NOT NULL,
    cmp_id             BIGINT       NOT NULL,
    contract_id        BIGINT       NOT NULL REFERENCES contracts (id) ON DELETE CASCADE,

    amendment_no       SMALLINT     NOT NULL,
    title              VARCHAR(255) NOT NULL,
    description        TEXT         NULL,
    effective_date     DATE         NULL,
    execution_date     DATE         NULL,

    status             VARCHAR(24)  NOT NULL DEFAULT 'draft',

    -- What this amendment changes, as {field: {from, to}}. Applying an
    -- amendment writes the new values onto the contract AND keeps this record,
    -- so the current position and its history are both readable.
    affected_fields    JSONB        NOT NULL DEFAULT '{}'::jsonb,
    affected_clauses   JSONB        NOT NULL DEFAULT '[]'::jsonb,
    affected_commercials JSONB      NOT NULL DEFAULT '{}'::jsonb,
    affected_obligations JSONB      NOT NULL DEFAULT '[]'::jsonb,

    applied_at         TIMESTAMP    NULL,
    applied_by         VARCHAR(64)  NULL,
    created_by         VARCHAR(64)  NULL,
    created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_amendment_no UNIQUE (contract_id, amendment_no),
    CONSTRAINT ck_amendment_status CHECK (status IN ('draft','under_review','awaiting_approval','awaiting_signature','executed','cancelled')),
    CONSTRAINT ck_amendment_no CHECK (amendment_no > 0),
    -- An executed amendment with no effective date cannot be ordered against
    -- its siblings, which is what "current effective position" depends on.
    CONSTRAINT ck_amendment_executed CHECK (status <> 'executed' OR effective_date IS NOT NULL)
);

CREATE INDEX idx_amendments_contract ON contract_amendments (contract_id, amendment_no);
CREATE INDEX idx_amendments_status ON contract_amendments (environment, cmp_id, status);

ALTER TABLE contract_documents
    ADD CONSTRAINT fk_contract_documents_amendment FOREIGN KEY (amendment_id)
    REFERENCES contract_amendments (id) ON DELETE CASCADE;

CREATE TABLE contract_terminations (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                  UUID         NOT NULL DEFAULT gen_random_uuid(),
    environment           VARCHAR(16)  NOT NULL,
    cmp_id                BIGINT       NOT NULL,
    contract_id           BIGINT       NOT NULL REFERENCES contracts (id) ON DELETE CASCADE,

    termination_type      VARCHAR(32)  NOT NULL,
    reason                TEXT         NULL,
    initiating_party      VARCHAR(16)  NOT NULL DEFAULT 'company',
    requested_date        DATE         NULL,
    effective_date        DATE         NULL,
    applicable_clause_id  BIGINT       NULL REFERENCES contract_clauses (id) ON DELETE SET NULL,

    notice_required_days  SMALLINT     NULL,
    notice_issued_date    DATE         NULL,
    notice_document_id    BIGINT       NULL REFERENCES contract_documents (id) ON DELETE SET NULL,

    settlement_amount     NUMERIC(18,2) NULL,
    settlement_currency   VARCHAR(3)   NULL,
    outstanding_obligations TEXT       NULL,
    asset_return_required BOOLEAN      NOT NULL DEFAULT FALSE,
    confidentiality_survives BOOLEAN   NOT NULL DEFAULT TRUE,
    data_deletion_required BOOLEAN     NOT NULL DEFAULT FALSE,
    closure_checklist     JSONB        NOT NULL DEFAULT '[]'::jsonb,

    status                VARCHAR(24)  NOT NULL DEFAULT 'draft',
    approved_by           VARCHAR(64)  NULL,
    approved_at           TIMESTAMP    NULL,
    completed_at          TIMESTAMP    NULL,
    created_by            VARCHAR(64)  NULL,
    created_at            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_termination_type CHECK (termination_type IN (
        'for_convenience','for_cause','mutual','expiry','breach','insolvency','other')),
    CONSTRAINT ck_termination_party CHECK (initiating_party IN ('company','counterparty','mutual')),
    CONSTRAINT ck_termination_status CHECK (status IN ('draft','pending_approval','approved','notice_issued','completed','cancelled')),
    CONSTRAINT ck_termination_currency CHECK (settlement_currency IS NULL OR settlement_currency ~ '^[A-Z]{3}$')
);

CREATE INDEX idx_terminations_contract ON contract_terminations (contract_id);
CREATE INDEX idx_terminations_status ON contract_terminations (environment, cmp_id, status);
