-- The risk engine: deterministic rules first, AI second.
--
-- Rules are evaluated against structured contract data and always produce the
-- same finding for the same input; AI findings are marked as such and carry a
-- confidence. Mixing them in one table with an explicit `detected_by` is what
-- lets a reviewer trust "unlimited liability" (a rule fired on a clause match)
-- differently from "this indemnity looks broad" (a model's reading).

CREATE TABLE contract_risk_rules (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    environment    VARCHAR(16)  NOT NULL,
    cmp_id         BIGINT       NOT NULL,

    rule_key       VARCHAR(64)  NOT NULL,
    name           VARCHAR(200) NOT NULL,
    description    TEXT         NULL,
    risk_category  VARCHAR(32)  NOT NULL,
    severity       VARCHAR(16)  NOT NULL DEFAULT 'medium',

    -- What to look at and how. `subject` names the evaluator branch in
    -- RiskRuleEngine; keeping it an enum rather than an expression means a rule
    -- can never become arbitrary code.
    subject        VARCHAR(48)  NOT NULL,
    operator       VARCHAR(24)  NOT NULL,
    value_text     TEXT         NULL,
    value_numeric  NUMERIC(18,2) NULL,
    value_list     JSONB        NOT NULL DEFAULT '[]'::jsonb,

    applies_to_types JSONB      NOT NULL DEFAULT '[]'::jsonb,
    score_weight   SMALLINT     NOT NULL DEFAULT 10,
    recommendation TEXT         NULL,
    is_system      BOOLEAN      NOT NULL DEFAULT FALSE,
    is_active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_risk_rules_key UNIQUE (environment, cmp_id, rule_key),
    CONSTRAINT ck_risk_rules_category CHECK (risk_category IN (
        'legal','commercial','financial','compliance','operational',
        'data_protection','renewal','counterparty','sla')),
    CONSTRAINT ck_risk_rules_severity CHECK (severity IN ('informational','low','medium','high','critical')),
    CONSTRAINT ck_risk_rules_subject CHECK (subject IN (
        'clause_text','clause_missing','liability_cap','auto_renewal','notice_period',
        'governing_law','jurisdiction','payment_terms','contract_value','duration_months',
        'termination_right','indemnity','data_protection','insurance','sla_defined',
        'expiry_date','counterparty_missing','signature_missing','document_missing')),
    CONSTRAINT ck_risk_rules_operator CHECK (operator IN (
        'contains','not_contains','equals','not_equals','greater_than','less_than',
        'in_list','not_in_list','is_true','is_false','is_null','is_not_null','regex')),
    CONSTRAINT ck_risk_rules_weight CHECK (score_weight BETWEEN 0 AND 100)
);

CREATE INDEX idx_risk_rules_tenant ON contract_risk_rules (environment, cmp_id, is_active);

CREATE TABLE contract_risk_assessments (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid           UUID         NOT NULL DEFAULT gen_random_uuid(),
    environment    VARCHAR(16)  NOT NULL,
    cmp_id         BIGINT       NOT NULL,
    contract_id    BIGINT       NOT NULL REFERENCES contracts (id) ON DELETE CASCADE,
    version_id     BIGINT       NULL REFERENCES contract_document_versions (id) ON DELETE SET NULL,

    overall_score  SMALLINT     NOT NULL DEFAULT 0,
    risk_level     VARCHAR(16)  NOT NULL DEFAULT 'low',
    category_scores JSONB       NOT NULL DEFAULT '{}'::jsonb,
    health_score   SMALLINT     NULL,
    health_breakdown JSONB      NOT NULL DEFAULT '{}'::jsonb,

    findings_count SMALLINT     NOT NULL DEFAULT 0,
    critical_count SMALLINT     NOT NULL DEFAULT 0,
    high_count     SMALLINT     NOT NULL DEFAULT 0,

    engine_version VARCHAR(16)  NOT NULL DEFAULT '1',
    ai_used        BOOLEAN      NOT NULL DEFAULT FALSE,
    summary        TEXT         NULL,
    is_current     BOOLEAN      NOT NULL DEFAULT TRUE,
    generated_by   VARCHAR(64)  NULL,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_risk_assessment_score CHECK (overall_score BETWEEN 0 AND 100),
    CONSTRAINT ck_risk_assessment_health CHECK (health_score IS NULL OR health_score BETWEEN 0 AND 100),
    CONSTRAINT ck_risk_assessment_level CHECK (risk_level IN ('low','medium','high','critical'))
);

CREATE INDEX idx_risk_assessments_contract ON contract_risk_assessments (contract_id, created_at DESC);
-- One current assessment per contract: a stale "current" alongside a fresh one
-- would make the dashboard's risk counts depend on row order.
CREATE UNIQUE INDEX uq_risk_assessment_current ON contract_risk_assessments (contract_id) WHERE is_current;

CREATE TABLE contract_risk_findings (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id  BIGINT       NOT NULL REFERENCES contract_risk_assessments (id) ON DELETE CASCADE,
    contract_id    BIGINT       NOT NULL REFERENCES contracts (id) ON DELETE CASCADE,
    environment    VARCHAR(16)  NOT NULL,
    cmp_id         BIGINT       NOT NULL,

    rule_id        BIGINT       NULL REFERENCES contract_risk_rules (id) ON DELETE SET NULL,
    rule_key       VARCHAR(64)  NULL,
    clause_id      BIGINT       NULL REFERENCES contract_clauses (id) ON DELETE SET NULL,

    risk_category  VARCHAR(32)  NOT NULL,
    severity       VARCHAR(16)  NOT NULL,
    title          VARCHAR(255) NOT NULL,
    detail         TEXT         NULL,
    source_excerpt TEXT         NULL,
    source_page    SMALLINT     NULL,
    recommendation TEXT         NULL,

    detected_by    VARCHAR(16)  NOT NULL DEFAULT 'rules',
    ai_confidence  NUMERIC(4,3) NULL,
    score_impact   SMALLINT     NOT NULL DEFAULT 0,

    review_status  VARCHAR(24)  NOT NULL DEFAULT 'open',
    reviewed_by    VARCHAR(64)  NULL,
    reviewed_at    TIMESTAMP    NULL,
    review_notes   TEXT         NULL,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_risk_findings_category CHECK (risk_category IN (
        'legal','commercial','financial','compliance','operational',
        'data_protection','renewal','counterparty','sla')),
    CONSTRAINT ck_risk_findings_severity CHECK (severity IN ('informational','low','medium','high','critical')),
    CONSTRAINT ck_risk_findings_detected CHECK (detected_by IN ('rules','ai','manual')),
    CONSTRAINT ck_risk_findings_review CHECK (review_status IN ('open','accepted','mitigated','false_positive','resolved'))
);

CREATE INDEX idx_risk_findings_assessment ON contract_risk_findings (assessment_id, severity);
CREATE INDEX idx_risk_findings_contract ON contract_risk_findings (contract_id, review_status);
CREATE INDEX idx_risk_findings_tenant ON contract_risk_findings (environment, cmp_id, severity, review_status);
