-- Signature requests.
--
-- No proprietary cryptography here. Contracts records who must sign, tracks
-- status, and stores the provider's own reference and evidence certificate.
-- Providers plug in behind SignatureProviderInterface; with none configured a
-- company still gets the honest path — sign outside the system and upload the
-- executed copy.

CREATE TABLE signature_requests (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                UUID         NOT NULL DEFAULT gen_random_uuid(),
    environment         VARCHAR(16)  NOT NULL,
    cmp_id              BIGINT       NOT NULL,
    contract_id         BIGINT       NOT NULL REFERENCES contracts (id) ON DELETE CASCADE,
    amendment_id        BIGINT       NULL REFERENCES contract_amendments (id) ON DELETE CASCADE,
    document_version_id BIGINT       NULL REFERENCES contract_document_versions (id) ON DELETE SET NULL,

    provider            VARCHAR(32)  NOT NULL DEFAULT 'manual',
    provider_reference  VARCHAR(160) NULL,
    status              VARCHAR(24)  NOT NULL DEFAULT 'draft',
    is_sequential       BOOLEAN      NOT NULL DEFAULT TRUE,

    subject             VARCHAR(255) NULL,
    message             TEXT         NULL,
    expires_at          TIMESTAMP    NULL,
    sent_at             TIMESTAMP    NULL,
    completed_at        TIMESTAMP    NULL,
    cancelled_at        TIMESTAMP    NULL,
    decline_reason      TEXT         NULL,

    executed_document_id BIGINT      NULL REFERENCES contract_documents (id) ON DELETE SET NULL,
    evidence_reference  VARCHAR(255) NULL,

    created_by          VARCHAR(64)  NULL,
    created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_signature_status CHECK (status IN (
        'draft','sent','viewed','partially_signed','signed','declined','expired','cancelled','completed'))
);

CREATE INDEX idx_signature_requests_contract ON signature_requests (contract_id);
CREATE INDEX idx_signature_requests_status ON signature_requests (environment, cmp_id, status);
CREATE INDEX idx_signature_requests_stale ON signature_requests (status, sent_at) WHERE status IN ('sent','viewed','partially_signed');

CREATE TABLE signature_signers (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id    BIGINT       NOT NULL REFERENCES signature_requests (id) ON DELETE CASCADE,
    environment   VARCHAR(16)  NOT NULL,
    cmp_id        BIGINT       NOT NULL,
    party_id      BIGINT       NULL REFERENCES contract_parties (id) ON DELETE SET NULL,

    signer_order  SMALLINT     NOT NULL DEFAULT 1,
    name          VARCHAR(160) NOT NULL,
    email         VARCHAR(255) NULL,
    phone         VARCHAR(48)  NULL,
    designation   VARCHAR(160) NULL,
    side          VARCHAR(16)  NOT NULL DEFAULT 'counterparty',

    status        VARCHAR(24)  NOT NULL DEFAULT 'pending',
    sent_at       TIMESTAMP    NULL,
    viewed_at     TIMESTAMP    NULL,
    signed_at     TIMESTAMP    NULL,
    declined_at   TIMESTAMP    NULL,
    decline_reason TEXT        NULL,
    provider_signer_ref VARCHAR(160) NULL,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_signature_signer_status CHECK (status IN ('pending','sent','viewed','signed','declined','expired')),
    CONSTRAINT ck_signature_signer_side CHECK (side IN ('company','counterparty','witness','other'))
);

CREATE INDEX idx_signature_signers_request ON signature_signers (request_id, signer_order);

-- Inbound provider callbacks. Stored before they are acted on so a duplicate
-- delivery is a no-op rather than a second state transition — every provider
-- retries, and none guarantees exactly-once.
CREATE TABLE signature_webhook_events (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    environment   VARCHAR(16)  NOT NULL,
    provider      VARCHAR(32)  NOT NULL,
    event_id      VARCHAR(160) NOT NULL,
    request_id    BIGINT       NULL REFERENCES signature_requests (id) ON DELETE SET NULL,
    event_type    VARCHAR(64)  NULL,
    payload       JSONB        NOT NULL DEFAULT '{}'::jsonb,
    signature_valid BOOLEAN    NOT NULL DEFAULT FALSE,
    processed_at  TIMESTAMP    NULL,
    error_message TEXT         NULL,
    received_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_signature_webhook_event UNIQUE (provider, event_id)
);

CREATE INDEX idx_signature_webhooks_unprocessed ON signature_webhook_events (processed_at) WHERE processed_at IS NULL;
