-- The Contracts AI subsystem.
--
-- Contracts owns its AI logic; Console owns the provider credentials. Nothing
-- here stores an API key. What it does store is every job, every raw model
-- response, and whether a human has confirmed the result — because an
-- extraction nobody checked is a suggestion, not a contract term, and the
-- product has to be able to tell the difference.

CREATE TABLE ai_jobs (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid           UUID         NOT NULL DEFAULT gen_random_uuid(),
    environment    VARCHAR(16)  NOT NULL,
    cmp_id         BIGINT       NOT NULL,

    kind           VARCHAR(32)  NOT NULL,
    contract_id    BIGINT       NULL REFERENCES contracts (id) ON DELETE CASCADE,
    version_id     BIGINT       NULL REFERENCES contract_document_versions (id) ON DELETE CASCADE,
    payload        JSONB        NOT NULL DEFAULT '{}'::jsonb,

    status         VARCHAR(16)  NOT NULL DEFAULT 'queued',
    attempts       SMALLINT     NOT NULL DEFAULT 0,
    max_attempts   SMALLINT     NOT NULL DEFAULT 3,
    -- Set while a worker holds the job. A crashed worker's lock ages out, which
    -- is what stops a job being lost rather than merely delayed.
    locked_at      TIMESTAMP    NULL,
    locked_by      VARCHAR(64)  NULL,
    next_attempt_at TIMESTAMP   NULL,

    provider       VARCHAR(32)  NULL,
    model          VARCHAR(96)  NULL,
    prompt_tokens  INTEGER      NULL,
    output_tokens  INTEGER      NULL,
    latency_ms     INTEGER      NULL,

    result         JSONB        NULL,
    error_code     VARCHAR(64)  NULL,
    error_message  TEXT         NULL,

    -- Same (kind, subject, input hash) means the same answer; a repeat request
    -- returns the existing job instead of paying for the model again.
    idempotency_key VARCHAR(96) NULL,

    requested_by   VARCHAR(64)  NULL,
    started_at     TIMESTAMP    NULL,
    completed_at   TIMESTAMP    NULL,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_ai_jobs_kind CHECK (kind IN (
        'extract','classify','summarize','clauses','obligations','risk',
        'compare','answer','renewal_advice','deviation')),
    CONSTRAINT ck_ai_jobs_status CHECK (status IN ('queued','running','succeeded','failed','cancelled')),
    CONSTRAINT ck_ai_jobs_attempts CHECK (attempts >= 0 AND max_attempts > 0)
);

CREATE UNIQUE INDEX uq_ai_jobs_idempotency ON ai_jobs (environment, cmp_id, idempotency_key) WHERE idempotency_key IS NOT NULL;
CREATE INDEX idx_ai_jobs_queue ON ai_jobs (status, next_attempt_at) WHERE status IN ('queued','running');
CREATE INDEX idx_ai_jobs_contract ON ai_jobs (contract_id, kind, created_at DESC);

-- Field-level extraction results. One row per field so the review queue can
-- highlight exactly which values are low-confidence, rather than presenting a
-- whole contract as "probably right".
CREATE TABLE ai_extractions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id         BIGINT       NULL REFERENCES ai_jobs (id) ON DELETE SET NULL,
    environment    VARCHAR(16)  NOT NULL,
    cmp_id         BIGINT       NOT NULL,
    contract_id    BIGINT       NOT NULL REFERENCES contracts (id) ON DELETE CASCADE,
    version_id     BIGINT       NULL REFERENCES contract_document_versions (id) ON DELETE SET NULL,

    field_key      VARCHAR(64)  NOT NULL,
    field_label    VARCHAR(160) NULL,
    extracted_value TEXT        NULL,
    normalised_value TEXT       NULL,
    value_type     VARCHAR(24)  NOT NULL DEFAULT 'text',
    confidence     NUMERIC(4,3) NULL,

    source_page    SMALLINT     NULL,
    source_excerpt TEXT         NULL,

    review_state   VARCHAR(24)  NOT NULL DEFAULT 'pending',
    accepted_value TEXT         NULL,
    reviewed_by    VARCHAR(64)  NULL,
    reviewed_at    TIMESTAMP    NULL,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_ai_extractions_confidence CHECK (confidence IS NULL OR confidence BETWEEN 0 AND 1),
    CONSTRAINT ck_ai_extractions_review CHECK (review_state IN ('pending','accepted','edited','rejected')),
    CONSTRAINT ck_ai_extractions_type CHECK (value_type IN ('text','number','currency','date','boolean','list','json'))
);

CREATE INDEX idx_ai_extractions_contract ON ai_extractions (contract_id, review_state);
CREATE INDEX idx_ai_extractions_low_confidence ON ai_extractions (environment, cmp_id, confidence) WHERE review_state = 'pending';

CREATE TABLE ai_contract_summaries (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    environment    VARCHAR(16)  NOT NULL,
    cmp_id         BIGINT       NOT NULL,
    contract_id    BIGINT       NOT NULL REFERENCES contracts (id) ON DELETE CASCADE,
    version_id     BIGINT       NULL REFERENCES contract_document_versions (id) ON DELETE SET NULL,
    job_id         BIGINT       NULL REFERENCES ai_jobs (id) ON DELETE SET NULL,

    -- The model's own output, kept verbatim. A human edit writes to
    -- `edited_sections`, so regenerating never destroys a reviewer's wording
    -- and reviewing never destroys the original for comparison.
    sections       JSONB        NOT NULL DEFAULT '{}'::jsonb,
    edited_sections JSONB       NULL,
    executive_summary TEXT      NULL,
    management_actions JSONB    NOT NULL DEFAULT '[]'::jsonb,

    provider       VARCHAR(32)  NULL,
    model          VARCHAR(96)  NULL,
    is_current     BOOLEAN      NOT NULL DEFAULT TRUE,
    edited_by      VARCHAR(64)  NULL,
    edited_at      TIMESTAMP    NULL,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_ai_summaries_contract ON ai_contract_summaries (contract_id, created_at DESC);
CREATE UNIQUE INDEX uq_ai_summary_current ON ai_contract_summaries (contract_id) WHERE is_current;

CREATE TABLE ai_conversations (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid         UUID         NOT NULL DEFAULT gen_random_uuid(),
    environment  VARCHAR(16)  NOT NULL,
    cmp_id       BIGINT       NOT NULL,
    contract_id  BIGINT       NULL REFERENCES contracts (id) ON DELETE CASCADE,
    user_uuid    VARCHAR(64)  NOT NULL,
    title        VARCHAR(255) NULL,
    scope        VARCHAR(24)  NOT NULL DEFAULT 'contract',
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_ai_conversations_scope CHECK (scope IN ('contract','portfolio'))
);

CREATE INDEX idx_ai_conversations_user ON ai_conversations (environment, cmp_id, user_uuid, updated_at DESC);

CREATE TABLE ai_messages (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT      NOT NULL REFERENCES ai_conversations (id) ON DELETE CASCADE,
    environment     VARCHAR(16) NOT NULL,
    cmp_id          BIGINT      NOT NULL,

    role            VARCHAR(16) NOT NULL,
    content         TEXT        NOT NULL,
    -- Where the answer came from in the contract, so a user can check it rather
    -- than take it on faith. An answer with no citations is presented as such.
    citations       JSONB       NOT NULL DEFAULT '[]'::jsonb,
    grounded        BOOLEAN     NOT NULL DEFAULT TRUE,
    provider        VARCHAR(32) NULL,
    model           VARCHAR(96) NULL,
    latency_ms      INTEGER     NULL,
    created_at      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_ai_messages_role CHECK (role IN ('user','assistant','system'))
);

CREATE INDEX idx_ai_messages_conversation ON ai_messages (conversation_id, created_at);

-- Every model call, whether or not it succeeded. This is the audit trail for
-- "what did AI do on this contract" and the input to per-company AI throttling.
CREATE TABLE ai_usage_log (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    environment   VARCHAR(16)  NOT NULL,
    cmp_id        BIGINT       NOT NULL,
    user_uuid     VARCHAR(64)  NULL,
    contract_id   BIGINT       NULL,
    job_id        BIGINT       NULL,

    operation     VARCHAR(32)  NOT NULL,
    provider      VARCHAR(32)  NULL,
    model         VARCHAR(96)  NULL,
    credential_source VARCHAR(16) NULL,
    prompt_tokens INTEGER      NULL,
    output_tokens INTEGER      NULL,
    latency_ms    INTEGER      NULL,
    success       BOOLEAN      NOT NULL DEFAULT TRUE,
    error_code    VARCHAR(64)  NULL,
    -- Truncated and never the full prompt: contract text is the customer's
    -- confidential material and does not belong in a telemetry table.
    error_message VARCHAR(500) NULL,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_ai_usage_tenant ON ai_usage_log (environment, cmp_id, created_at DESC);
CREATE INDEX idx_ai_usage_contract ON ai_usage_log (contract_id, created_at DESC);
