-- Cross-cutting platform tables: linked records, comments, activity, audit,
-- notifications, the job queue and rate limiting.

-- ---------------------------------------------------------------------------
-- Linked records — the ecosystem join, by reference only
-- ---------------------------------------------------------------------------
-- Contracts stores a pointer to a Books voucher or a Sales order; it never
-- copies the row. Copying would create a second source of truth that silently
-- diverges, and every one of those products already answers for its own data.
CREATE TABLE contract_linked_records (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    environment    VARCHAR(16)  NOT NULL,
    cmp_id         BIGINT       NOT NULL,
    contract_id    BIGINT       NOT NULL REFERENCES contracts (id) ON DELETE CASCADE,

    product_code   VARCHAR(32)  NOT NULL,
    record_type    VARCHAR(48)  NOT NULL,
    record_id      VARCHAR(96)  NOT NULL,
    label          VARCHAR(255) NULL,
    relationship   VARCHAR(32)  NOT NULL DEFAULT 'related',
    url            VARCHAR(512) NULL,
    metadata       JSONB        NOT NULL DEFAULT '{}'::jsonb,

    linked_by      VARCHAR(64)  NULL,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_linked_record UNIQUE (contract_id, product_code, record_type, record_id),
    CONSTRAINT ck_linked_relationship CHECK (relationship IN (
        'related','source','derived','invoice','payment','order','event','conversation','document'))
);

CREATE INDEX idx_linked_records_contract ON contract_linked_records (contract_id);
CREATE INDEX idx_linked_records_lookup ON contract_linked_records (environment, cmp_id, product_code, record_id);

-- ---------------------------------------------------------------------------
-- Comments
-- ---------------------------------------------------------------------------
CREATE TABLE contract_comments (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid          UUID         NOT NULL DEFAULT gen_random_uuid(),
    environment   VARCHAR(16)  NOT NULL,
    cmp_id        BIGINT       NOT NULL,
    contract_id   BIGINT       NOT NULL REFERENCES contracts (id) ON DELETE CASCADE,

    subject_type  VARCHAR(24)  NOT NULL DEFAULT 'contract',
    subject_id    BIGINT       NULL,
    parent_id     BIGINT       NULL REFERENCES contract_comments (id) ON DELETE CASCADE,

    author_uuid   VARCHAR(64)  NOT NULL,
    body          TEXT         NOT NULL,
    mentions      JSONB        NOT NULL DEFAULT '[]'::jsonb,

    is_resolved   BOOLEAN      NOT NULL DEFAULT FALSE,
    resolved_by   VARCHAR(64)  NULL,
    resolved_at   TIMESTAMP    NULL,
    edited_at     TIMESTAMP    NULL,
    deleted_at    TIMESTAMP    NULL,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_comments_subject CHECK (subject_type IN ('contract','clause','version','approval','obligation','risk_finding','amendment')),
    CONSTRAINT ck_comments_self_parent CHECK (parent_id IS NULL OR parent_id <> id)
);

CREATE INDEX idx_comments_contract ON contract_comments (contract_id, created_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX idx_comments_subject ON contract_comments (contract_id, subject_type, subject_id);

-- ---------------------------------------------------------------------------
-- Activity timeline (user-facing) vs audit log (compliance)
-- ---------------------------------------------------------------------------
-- Two tables on purpose. The timeline is a readable story with friendly labels
-- that can be trimmed; the audit log is append-only evidence with before/after
-- values that must not be. Merging them would mean either an unreadable
-- timeline or a mutable audit trail.
CREATE TABLE contract_activity_logs (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    environment   VARCHAR(16)  NOT NULL,
    cmp_id        BIGINT       NOT NULL,
    contract_id   BIGINT       NULL REFERENCES contracts (id) ON DELETE CASCADE,
    request_id    BIGINT       NULL REFERENCES contract_requests (id) ON DELETE CASCADE,

    actor_uuid    VARCHAR(64)  NULL,
    actor_label   VARCHAR(160) NULL,
    event_type    VARCHAR(64)  NOT NULL,
    summary       VARCHAR(500) NOT NULL,
    icon          VARCHAR(32)  NULL,
    metadata      JSONB        NOT NULL DEFAULT '{}'::jsonb,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_activity_contract ON contract_activity_logs (contract_id, created_at DESC);
CREATE INDEX idx_activity_tenant ON contract_activity_logs (environment, cmp_id, created_at DESC);

CREATE TABLE contract_audit_logs (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    environment   VARCHAR(16)  NOT NULL,
    cmp_id        BIGINT       NOT NULL,

    entity_type   VARCHAR(48)  NOT NULL,
    entity_id     BIGINT       NULL,
    contract_id   BIGINT       NULL,

    action        VARCHAR(64)  NOT NULL,
    field_name    VARCHAR(64)  NULL,
    old_value     TEXT         NULL,
    new_value     TEXT         NULL,
    changes       JSONB        NULL,

    actor_uuid    VARCHAR(64)  NULL,
    actor_ip      VARCHAR(64)  NULL,
    user_agent    VARCHAR(255) NULL,
    request_id    VARCHAR(64)  NULL,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_audit_entity ON contract_audit_logs (environment, cmp_id, entity_type, entity_id, created_at DESC);
CREATE INDEX idx_audit_contract ON contract_audit_logs (contract_id, created_at DESC);
CREATE INDEX idx_audit_actor ON contract_audit_logs (environment, cmp_id, actor_uuid, created_at DESC);

-- Deleting audit history has to be a deliberate, privileged, database-level act
-- rather than something an application bug or a stray DELETE can do.
REVOKE DELETE ON contract_audit_logs FROM PUBLIC;

CREATE OR REPLACE FUNCTION contract_audit_logs_immutable() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'contract_audit_logs is append-only; % is not permitted', TG_OP;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_contract_audit_logs_no_update
    BEFORE UPDATE OR DELETE ON contract_audit_logs
    FOR EACH ROW EXECUTE FUNCTION contract_audit_logs_immutable();

-- ---------------------------------------------------------------------------
-- Notifications
-- ---------------------------------------------------------------------------
CREATE TABLE contract_notifications (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid          UUID         NOT NULL DEFAULT gen_random_uuid(),
    environment   VARCHAR(16)  NOT NULL,
    cmp_id        BIGINT       NOT NULL,
    recipient_uuid VARCHAR(64) NOT NULL,

    event_type    VARCHAR(64)  NOT NULL,
    title         VARCHAR(255) NOT NULL,
    body          TEXT         NULL,
    severity      VARCHAR(16)  NOT NULL DEFAULT 'info',

    contract_id   BIGINT       NULL REFERENCES contracts (id) ON DELETE CASCADE,
    link_path     VARCHAR(255) NULL,
    metadata      JSONB        NOT NULL DEFAULT '{}'::jsonb,

    -- Same event + same recipient + same day = one notification. Without this
    -- a nightly sweep that runs twice tells everyone twice.
    dedupe_key    VARCHAR(160) NULL,

    read_at       TIMESTAMP    NULL,
    email_sent_at TIMESTAMP    NULL,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_notification_severity CHECK (severity IN ('info','success','warning','critical'))
);

CREATE UNIQUE INDEX uq_notification_dedupe ON contract_notifications (environment, cmp_id, recipient_uuid, dedupe_key)
    WHERE dedupe_key IS NOT NULL;
CREATE INDEX idx_notifications_recipient ON contract_notifications (environment, cmp_id, recipient_uuid, read_at, created_at DESC);

-- ---------------------------------------------------------------------------
-- Background job queue
-- ---------------------------------------------------------------------------
-- PostgreSQL-backed rather than Redis/SQS: the ecosystem runs on cPanel with
-- cron, adding a broker would be infrastructure nobody asked for, and
-- SKIP LOCKED gives correct concurrent dequeue at this volume.
CREATE TABLE contract_jobs (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    environment    VARCHAR(16)  NOT NULL,
    cmp_id         BIGINT       NULL,

    queue          VARCHAR(32)  NOT NULL DEFAULT 'default',
    job_type       VARCHAR(64)  NOT NULL,
    payload        JSONB        NOT NULL DEFAULT '{}'::jsonb,

    status         VARCHAR(16)  NOT NULL DEFAULT 'queued',
    priority       SMALLINT     NOT NULL DEFAULT 100,
    attempts       SMALLINT     NOT NULL DEFAULT 0,
    max_attempts   SMALLINT     NOT NULL DEFAULT 5,

    available_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    locked_at      TIMESTAMP    NULL,
    locked_by      VARCHAR(64)  NULL,
    started_at     TIMESTAMP    NULL,
    completed_at   TIMESTAMP    NULL,
    failed_at      TIMESTAMP    NULL,
    error_message  TEXT         NULL,

    idempotency_key VARCHAR(160) NULL,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_jobs_status CHECK (status IN ('queued','running','succeeded','failed','dead')),
    CONSTRAINT ck_jobs_attempts CHECK (attempts >= 0 AND max_attempts > 0)
);

CREATE UNIQUE INDEX uq_jobs_idempotency ON contract_jobs (environment, idempotency_key)
    WHERE idempotency_key IS NOT NULL AND status IN ('queued','running');
CREATE INDEX idx_jobs_dequeue ON contract_jobs (queue, status, priority, available_at) WHERE status = 'queued';
CREATE INDEX idx_jobs_stuck ON contract_jobs (status, locked_at) WHERE status = 'running';

-- A cron run records itself here so a sweep that already ran today does not run
-- again on a double-scheduled cron, and so an operator can see the last run.
CREATE TABLE contract_job_runs (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    environment   VARCHAR(16)  NOT NULL,
    task          VARCHAR(64)  NOT NULL,
    run_key       VARCHAR(96)  NOT NULL,
    started_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at   TIMESTAMP    NULL,
    processed     INTEGER      NOT NULL DEFAULT 0,
    notified      INTEGER      NOT NULL DEFAULT 0,
    errors        INTEGER      NOT NULL DEFAULT 0,
    detail        JSONB        NOT NULL DEFAULT '{}'::jsonb,

    CONSTRAINT uq_job_run_key UNIQUE (environment, task, run_key)
);

CREATE INDEX idx_job_runs_task ON contract_job_runs (environment, task, started_at DESC);

-- ---------------------------------------------------------------------------
-- Rate limiting
-- ---------------------------------------------------------------------------
-- In the database rather than in-process: PHP-FPM has many workers and APCu is
-- per-worker, so a per-process counter would let a caller multiply their budget
-- by the pool size. AI endpoints are the ones that cost real money.
CREATE TABLE contract_rate_limits (
    bucket_key   VARCHAR(255) PRIMARY KEY,
    window_start TIMESTAMP    NOT NULL,
    hits         INTEGER      NOT NULL DEFAULT 0,
    updated_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_rate_limits_window ON contract_rate_limits (window_start);

-- ---------------------------------------------------------------------------
-- Saved views
-- ---------------------------------------------------------------------------
CREATE TABLE contract_saved_views (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    environment  VARCHAR(16)  NOT NULL,
    cmp_id       BIGINT       NOT NULL,
    owner_uuid   VARCHAR(64)  NOT NULL,
    name         VARCHAR(120) NOT NULL,
    scope        VARCHAR(32)  NOT NULL DEFAULT 'repository',
    filters      JSONB        NOT NULL DEFAULT '{}'::jsonb,
    columns      JSONB        NOT NULL DEFAULT '[]'::jsonb,
    is_shared    BOOLEAN      NOT NULL DEFAULT FALSE,
    is_default   BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_saved_view_name UNIQUE (environment, cmp_id, owner_uuid, scope, name)
);

CREATE TABLE contract_favourites (
    environment VARCHAR(16) NOT NULL,
    cmp_id      BIGINT      NOT NULL,
    user_uuid   VARCHAR(64) NOT NULL,
    contract_id BIGINT      NOT NULL REFERENCES contracts (id) ON DELETE CASCADE,
    created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_uuid, contract_id)
);

CREATE TABLE contract_recent_views (
    environment VARCHAR(16) NOT NULL,
    cmp_id      BIGINT      NOT NULL,
    user_uuid   VARCHAR(64) NOT NULL,
    contract_id BIGINT      NOT NULL REFERENCES contracts (id) ON DELETE CASCADE,
    viewed_at   TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_uuid, contract_id)
);

CREATE INDEX idx_recent_views_user ON contract_recent_views (environment, cmp_id, user_uuid, viewed_at DESC);
