<?php

declare(strict_types=1);

/**
 * Apply pending SQL migrations.
 *
 *   php database/migrate.php            apply everything pending
 *   php database/migrate.php --status   list applied/pending and change nothing
 *   php database/migrate.php --seed     also apply database/seeds/*.sql (dev only)
 *
 * Each file runs inside one transaction: a migration either lands whole or not
 * at all, so a half-applied schema is not a state this product can reach.
 * Files are applied in filename order and recorded in `contracts_migration`,
 * which is what makes re-running safe.
 */

$root = dirname(__DIR__);

$autoload = $root . '/vendor/autoload.php';
if (is_readable($autoload)) {
    require_once $autoload;
} else {
    require_once $root . '/app/Core/Autoloader.php';
    \App\Core\Autoloader::register($root . '/app');
}

use App\Core\Database;
use App\Core\Env;

Env::setApiRoot($root);

$args     = array_slice($argv, 1);
$statusOnly = in_array('--status', $args, true);
$withSeeds  = in_array('--seed', $args, true);

$pdo = Database::pdo();
if ($pdo === null) {
    fwrite(STDERR, "Cannot connect to the database.\n");
    fwrite(STDERR, Database::unavailableMessage() . "\n");
    exit(1);
}

$pdo->exec('CREATE TABLE IF NOT EXISTS contracts_migration (
    batch       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename    VARCHAR(255) NOT NULL,
    executed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_contracts_migration_file UNIQUE (filename)
)');

/** @return list<string> */
function collect(string $dir): array
{
    $list = glob($dir . '/*.sql');

    if ($list === false) {
        return [];
    }
    sort($list);

    return $list;
}

$files = collect($root . '/database/migrations');
if ($withSeeds) {
    $files = array_merge($files, collect($root . '/database/seeds'));
}

if ($files === []) {
    fwrite(STDERR, "No migration files found.\n");
    exit(1);
}

$applied = [];
foreach ($pdo->query('SELECT filename FROM contracts_migration')->fetchAll() as $row) {
    $applied[(string) $row['filename']] = true;
}

if ($statusOnly) {
    foreach ($files as $file) {
        $name = basename($file);
        printf("%-12s %s\n", isset($applied[$name]) ? 'applied' : 'PENDING', $name);
    }
    exit(0);
}

$count = 0;
foreach ($files as $file) {
    $name = basename($file);
    if (isset($applied[$name])) {
        continue;
    }

    $sql = file_get_contents($file);
    if (! is_string($sql)) {
        fwrite(STDERR, "Cannot read {$name}\n");
        exit(1);
    }

    $pdo->beginTransaction();
    foreach (Database::splitSqlStatements($sql) as $statement) {
        try {
            $pdo->exec($statement);
        } catch (Throwable $e) {
            $pdo->rollBack();
            fwrite(STDERR, "Failed {$name}: " . $e->getMessage() . "\n");
            fwrite(STDERR, "Statement: " . substr($statement, 0, 400) . "\n");
            exit(1);
        }
    }
    $pdo->prepare('INSERT INTO contracts_migration (filename) VALUES (?)')->execute([$name]);
    $pdo->commit();

    echo "Applied {$name}\n";
    $count++;
}

echo $count === 0 ? "Nothing to apply.\n" : "Done — {$count} migration(s) applied.\n";
